// GENERATED by node scripts/build-backend.js. Edit backend/src instead.

// --- modules/records/domain/record.js ---
// Immutable value object. Storage, transport and framework independent.
function RecordDraft(input) {
  const number = value => value !== null && value !== undefined && String(value).trim() !== '' && Number.isFinite(Number(value));
  const url = value => !value || /^https?:\/\/[^\s<>"'`]+$/i.test(String(value).trim());
  const trustedVideoUrl = value => !value || /^https?:\/\/(?:(?:www\.|m\.)?(?:youtube\.com|youtu\.be)|(?:www\.)?twitch\.tv|clips\.twitch\.tv|(?:www\.)?vimeo\.com|player\.vimeo\.com|(?:www\.)?tiktok\.com|vm\.tiktok\.com|(?:www\.)?kick\.com|(?:www\.)?facebook\.com|fb\.watch|(?:www\.)?instagram\.com)\//i.test(String(value).trim());
  if (!["sem_ajuda", "com_ajuda"].includes(input.method)) throw new Error("Informe o método: sem_ajuda ou com_ajuda");
  if (!["normal", "natural"].includes(input.wind)) throw new Error("Informe o vento: normal ou natural");
  if (!number(input.score) || !Number.isInteger(Number(input.score))) throw new Error("Score inválido");
  if (!number(input.power_value) || Number(input.power_value) <= 0) throw new Error("Força inválida");
  if (input.pang !== undefined && input.pang !== '' && (!number(input.pang) || Number(input.pang) < 0 || !Number.isInteger(Number(input.pang)))) throw new Error("Pang inválido");
  if (!String(input.course_id || '').trim()) throw new Error("Informe o campo");
  if (!url(input.screenshot_url)) throw new Error("URL do print inválida (use http/https)");
  if (!trustedVideoUrl(input.video_url)) throw new Error("Use um link de vídeo do YouTube, Twitch, Vimeo, TikTok, Kick, Facebook ou Instagram");
  if (input.method === "sem_ajuda" && !String(input.video_url || '').trim()) throw new Error("Sem ajuda exige vídeo de prova");
  return Object.freeze({
    course_id: String(input.course_id), power_value: Number(input.power_value),
    score: Number(input.score), pang: Number(input.pang || 0),
    method: input.method, wind: input.wind,
    screenshot_url: String(input.screenshot_url || '').trim(), video_url: String(input.video_url || '').trim(),
  });
}

// --- modules/records/domain/ranking.js ---
const RecordPolicy = Object.freeze({
  compare: (a, b) => Number(a.score) - Number(b.score) || Number(b.pang || 0) - Number(a.pang || 0),
  isPublished: record => record.status === "approved" && Number(record.community) === 1,
});

// --- modules/community/domain/voting.js ---
const VotingPolicy = Object.freeze({
  decide(tally) {
    if (tally.voters < 3) return null;
    if (tally.approve >= 50 && tally.approve > 2 * tally.reject) return "approved";
    if (tally.reject >= 50 && tally.reject > 2 * tally.approve) return "rejected";
    return null;
  }
});

// --- modules/identity/domain/points.js ---
function effectivePoints(u, now) {
  // bônus por eventos +5/mês de conta (teto 60 = 12 meses). Vale como peso do voto.
  const bonus = Number(u.points || 0);
  let months = 0;
  const created = new Date(u.created_at);
  if (!isNaN(created)) {
    months = (now.getFullYear() - created.getFullYear()) * 12 + (now.getMonth() - created.getMonth());
    if (now.getDate() < created.getDate()) months--;
    months = Math.max(0, Math.min(12, months));
  }
  return bonus + months * 5;
}

// --- infrastructure/google-apps-script.js ---
const SALT = "TROQUE_ISSO_salt_bem_longo"; // usado no hash da senha
const SESSION_DIAS = 30;
const SESSION_IDLE_MINUTES = 30;
const SESSION_HEARTBEAT_MINUTES = 5;
const LOGIN_MAX_ATTEMPTS = 5;
const LOGIN_WINDOW_SECONDS = 5 * 60;
// Login Google (GIS): Client ID é público por desenho (vai no JS). Troque pelo seu
// (console.cloud.google.com → APIs e serviços → Credenciais → ID do cliente OAuth).
const GOOGLE_CLIENT_ID = "TROQUE_ISSO_google_client_id"; // igual ao frontend/js/config.js
// Nunca vai para o frontend. Copie do mesmo cliente OAuth Web no Console Google.
const GOOGLE_CLIENT_SECRET = "TROQUE_ISSO_google_client_secret";
const GOOGLE_REDIRECT_ORIGINS = ["https://acrisio-filho.github.io", "http://localhost:8080"];
// Comunidade: voto pesa os pontos; aprova com peso 50+, 3+ votantes e >2x o contrário
const VOTE_QUORUM = 50;
const VOTE_MIN_VOTERS = 3;
const PTS_ADMIN_OK = 10; // record aceito pelo admin
const PTS_COM_OK = 25; // record aceito pela comunidade (vale mais)
const PTS_IMPROVE_ADMIN = 5; // melhoria aprovada (metade)
const PTS_IMPROVE_COM = 12; // melhoria aceita pela comunidade (metade)
// Método do record: sem_ajuda (só o jogo aberto, vídeo obrigatório) ou com_ajuda (programas)
const METHODS = ["sem_ajuda", "com_ajuda"];
// Vento: normal ou natural (parte da categoria, como o método)
const WINDS = ["normal", "natural"];
// Cache de snapshots das abas: reduz chamadas caras ao Sheets nas leituras
// públicas. Toda escrita abaixo invalida a respectiva aba imediatamente.
// O limite individual do CacheService é 100 KB. Snapshots são compactados
// quando necessário para manter Records no cache mesmo em planilhas maiores.
const SHEET_CACHE_TTL_SECONDS = 5 * 60;
const SHEET_CACHE_MAX_BYTES = 90 * 1024;
function _methodLabel(m) {
  return m === "sem_ajuda" ? "Sem ajuda" : m === "com_ajuda" ? "Com ajuda" : String(m || "");
}

function _out(obj) {
  return ContentService.createTextOutput(JSON.stringify(obj)).setMimeType(ContentService.MimeType.JSON);
}
function _ss() { return SpreadsheetApp.getActiveSpreadsheet(); }
function _sheet(name) { return _ss().getSheetByName(name); }
function _sheetCache() {
  try { return typeof CacheService !== "undefined" ? CacheService.getScriptCache() : null; } catch (_) { return null; }
}
function _sheetCacheKey(name) { return "pwr:snapshot:v2:" + String(name); }
function _clearSheetCache(name) {
  const cache = _sheetCache();
  if (!cache) return;
  try { cache.remove(_sheetCacheKey(name)); } catch (_) { /* cache é opcional */ }
}
function _loginCacheKey(email) { return "pwr:login-attempts:v1:" + _hash(String(email || "").toLowerCase().trim()); }
function _loginBlocked(email) {
  const cache = _sheetCache();
  if (!cache) return false;
  try {
    const raw = cache.get(_loginCacheKey(email));
    const data = raw ? JSON.parse(raw) : null;
    return !!data && Number(data.failures || 0) >= LOGIN_MAX_ATTEMPTS;
  } catch (_) { return false; }
}
function _registerFailedLogin(email) {
  const cache = _sheetCache();
  if (!cache) return;
  try {
    const key = _loginCacheKey(email);
    const current = JSON.parse(cache.get(key) || "{}");
    cache.put(key, JSON.stringify({ failures: Number(current.failures || 0) + 1 }), LOGIN_WINDOW_SECONDS);
  } catch (_) { /* proteção adicional: login continua disponível se o cache falhar */ }
}
function _clearFailedLogins(email) {
  const cache = _sheetCache();
  if (!cache) return;
  try { cache.remove(_loginCacheKey(email)); } catch (_) { /* cache é opcional */ }
}
function _readSheetSnapshot(value) {
  if (!String(value).startsWith("gz:")) return JSON.parse(value);
  const bytes = Utilities.base64DecodeWebSafe(String(value).slice(3));
  return JSON.parse(Utilities.ungzip(Utilities.newBlob(bytes)).getDataAsString());
}
function _writeSheetSnapshot(rows) {
  const plain = JSON.stringify(rows);
  if (plain.length <= SHEET_CACHE_MAX_BYTES) return plain;
  const compressed = Utilities.base64EncodeWebSafe(Utilities.gzip(Utilities.newBlob(plain, "application/json")).getBytes());
  return compressed.length <= SHEET_CACHE_MAX_BYTES ? "gz:" + compressed : "";
}
function _rows(name) {
  const cache = _sheetCache();
  const key = _sheetCacheKey(name);
  if (cache) {
    try {
      const saved = cache.get(key);
      if (saved) {
        const v = _readSheetSnapshot(saved);
        return v.length ? { header: v[0], rows: v.slice(1) } : { header: [], rows: [] };
      }
    } catch (_) { /* dado expirado/corrompido: lê a planilha normalmente */ }
  }
  const sh = _sheet(name);
  if (!sh) return { header: [], rows: [] };
  const v = sh.getDataRange().getValues();
  if (cache && v.length) {
    try {
      const serialized = _writeSheetSnapshot(v);
      if (serialized) cache.put(key, serialized, SHEET_CACHE_TTL_SECONDS);
    } catch (_) { /* cache é otimização, nunca bloqueia a leitura */ }
  }
  if (v.length === 0) return { header: [], rows: [] };
  return { header: v[0], rows: v.slice(1) };
}
function _toObj(header, r) {
  const o = {};
  header.forEach((c, i) => { o[String(c)] = r[i]; });
  return o;
}
// Paginação: com limit=N retorna { rows, total }; sem limit retorna o array (compatível).
function _page(arr, p) {
  const raw = Number(p.limit) || 0;
  if (!raw) return arr;
  const lim = Math.min(200, Math.max(1, raw));
  const off = Math.max(0, Number(p.offset) || 0);
  return { rows: arr.slice(off, off + lim), total: arr.length };
}
function _append(name, obj, header) {
  _sheet(name).appendRow(header.map(h => obj[h] !== undefined ? obj[h] : ""));
  _clearSheetCache(name);
}
function _hash(s) {
  const bytes = Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256, SALT + s);
  return bytes.map(b => ("0" + ((b < 0 ? b + 256 : b)).toString(16)).slice(-2)).join("");
}
function _publicUser(u) {
  return { id: u.id, nickname: u.nickname, role: u.role, status: u.status || "active", bio: u.bio || "", youtube_url: u.youtube_url || "", avatar_url: u.avatar_url || "", has_password: !!u.pass_hash, points: _effPoints(u), created_at: u.created_at };
}
function _effPoints(u) { return effectivePoints(u, new Date()); }
function _addPoints(userId, pts) {
  const sh = _sheet("Users");
  const vals = sh.getDataRange().getValues();
  const head = vals[0];
  const ci = head.indexOf("points");
  if (ci < 0) return;
  for (let i = 1; i < vals.length; i++) {
    if (String(vals[i][0]) === String(userId)) {
      sh.getRange(i + 1, ci + 1).setValue(Number(vals[i][ci] || 0) + pts);
      _clearSheetCache("Users");
      return;
    }
  }
}
function _tally(recordId) {
  const { header, rows } = _rows("Votes");
  let approve = 0, reject = 0;
  const voters = {};
  rows.forEach(r => {
    const v = _toObj(header, r);
    if (String(v.record_id) !== String(recordId)) return;
    voters[String(v.user_id)] = 1;
    if (v.vote === "approve") approve += Number(v.weight || 0);
    else reject += Number(v.weight || 0);
  });
  return { approve, reject, voters: Object.keys(voters).length };
}
function _youtubeOk(u) {
  // canal: só YouTube (youtube.com / youtu.be), outros sites bloqueados
  return /^(https?:\/\/)?(www\.|m\.)?(youtube\.com|youtu\.be)\//i.test(String(u || "").trim());
}
function _urlOk(u) {
  // print/vídeo são opcionais (vazio ok); preenchidos: só http(s), sem espaços/<>"/'
  // p/ barrar javascript:/data: e quebra de atributo HTML
  u = String(u == null ? "" : u).trim();
  return u === "" || /^https?:\/\/[^\s<>"'`]+$/i.test(u);
}
function _findUserByEmail(email) {
  const { header, rows } = _rows("Users");
  email = String(email).toLowerCase().trim();
  for (const r of rows) {
    const u = _toObj(header, r);
    if (String(u.email).toLowerCase() === email) return u;
  }
  return null;
}
function _findUserById(id) {
  const { header, rows } = _rows("Users");
  for (const r of rows) {
    const u = _toObj(header, r);
    if (String(u.id) === String(id)) return u;
  }
  return null;
}
function _getSession(token) {
  if (!token) return null;
  const { header, rows } = _rows("Sessions");
  const lastSeenIndex = header.indexOf("last_seen_at");
  const now = new Date();
  for (let i = 0; i < rows.length; i++) {
    const r = rows[i];
    const s = _toObj(header, r);
    if (String(s.token) === String(token)) {
      const expired = new Date(s.expires_at) < now;
      const lastSeen = lastSeenIndex >= 0 && s.last_seen_at ? new Date(s.last_seen_at) : null;
      const idle = lastSeen && now - lastSeen > SESSION_IDLE_MINUTES * 60 * 1000;
      if (expired || idle) {
        _sheet("Sessions").deleteRow(i + 2);
        _clearSheetCache("Sessions");
        return null;
      }
      // Não grava a cada request: a sessão continua sendo encerrada após 30 min
      // sem atividade, com precisão de até cinco minutos e menos I/O no Sheets.
      if (lastSeenIndex >= 0 && (!lastSeen || now - lastSeen >= SESSION_HEARTBEAT_MINUTES * 60 * 1000)) {
        _sheet("Sessions").getRange(i + 2, lastSeenIndex + 1).setValue(now.toISOString());
        _clearSheetCache("Sessions");
      }
      return s;
    }
  }
  return null;
}
function _pruneSessions() {
  // higiene: apaga sessões expiradas p/ a aba não crescer p/ sempre
  const sh = _sheet("Sessions");
  const vals = sh.getDataRange().getValues();
  const ei = vals[0].indexOf("expires_at");
  if (ei < 0) return;
  const now = new Date();
  for (let i = vals.length - 1; i >= 1; i--) {
    if (new Date(vals[i][ei]) < now) { sh.deleteRow(i + 1); _clearSheetCache("Sessions"); }
  }
}
function _newSession(userId) {
  _pruneSessions();
  const token = Utilities.getUuid();
  const exp = new Date(); exp.setDate(exp.getDate() + SESSION_DIAS);
  const { header } = _rows("Sessions");
  _append("Sessions", { token, user_id: userId, expires_at: exp.toISOString(), last_seen_at: new Date().toISOString() }, header);
  return token;
}
function _authUser(e, payload) {
  const token = (e.parameter && e.parameter.token) || (payload && payload.token);
  const s = _getSession(token);
  if (!s) return null;
  return _findUserById(s.user_id);
}
function _isAdmin(e) {
  const u = _authUser(e, null);
  return u && u.role === "admin";
}
function _isLiveRow(head, r) {
  // live no index: approved + comunidade aprovou
  return RecordPolicy.isPublished(_toObj(head, r));
}
function _makeProposal(sh, head, col, origIdx, vals, u, data, preserveCommunity = false) {
  // Melhoria de record live: cria linha pendente ligada ao original (que segue valendo).
  const o = _toObj(head, vals[origIdx]);
  const rec = {
    id: Utilities.getUuid(), user_id: u.id, edit_of: String(o.id),
    course_id: String(data.course_id !== undefined ? data.course_id : o.course_id),
    powerband_id: String(data.powerband_id !== undefined ? data.powerband_id : o.powerband_id),
    power_value: Number(data.power_value !== undefined ? data.power_value : o.power_value),
    score: Number(data.score !== undefined ? data.score : o.score),
    pang: Number(data.pang !== undefined ? data.pang : (o.pang || 0)),
    method: String(data.method !== undefined ? data.method : (o.method || "com_ajuda")),
    wind: String(data.wind !== undefined ? data.wind : (o.wind || "normal")),
    screenshot_url: String(data.screenshot_url !== undefined ? data.screenshot_url : (o.screenshot_url || "")),
    video_url: String(data.video_url !== undefined ? data.video_url : (o.video_url || "")),
    status: "pending", submitted_at: new Date().toISOString(), validated_by: "", validated_at: "",
    // Mudança apenas nas provas ainda exige aprovação do admin, mas não
    // descarta uma aprovação comunitária já obtida pelo mesmo score/Pang.
    note: "", is_best: "", community: preserveCommunity ? "1" : "0", pts_admin: "", pts_com: "", edited: "TRUE"
  };
  const { header } = _rows("Records");
  _append("Records", rec, header);
  return rec.id;
}
function _bandForPower(power) {
  const { header, rows } = _rows("PowerBands");
  for (const r of rows) {
    const b = _toObj(header, r);
    if (String(b.active).toUpperCase() === "TRUE" && Number(power) >= Number(b.min) && Number(power) <= Number(b.max)) return b;
  }
  return null;
}
function _recalcBest(courseId, bandId, method, wind) {
  // Melhor da categoria (course+faixa+método+vento) entre os aprovados PELA COMUNIDADE:
  // menor score, empate → maior pang. Marca is_best.
  const sh = _sheet("Records");
  const vals = sh.getDataRange().getValues();
  if (vals.length < 2) return;
  const head = vals[0];
  const ci = head.indexOf("is_best");
  if (ci < 0) return;
  const col = n => head.indexOf(n);
  const mi = head.indexOf("method");
  const wi = head.indexOf("wind");
  const coi = head.indexOf("community");
  const idx = [];
  const inCat = {};
  for (let i = 1; i < vals.length; i++) {
    if (String(vals[i][col("course_id")]) === String(courseId) && String(vals[i][col("powerband_id")]) === String(bandId) && String(vals[i][col("status")]) === "approved" && (mi < 0 || String(vals[i][mi]) === String(method)) && (wi < 0 || String(vals[i][wi]) === String(wind)) && (coi < 0 || Number(vals[i][coi] || 0) === 1)) idx.push(i);
  }
  idx.forEach(i => { inCat[i] = 1; });
  let best = -1;
  idx.forEach(i => {
    if (best < 0) { best = i; return; }
    if (RecordPolicy.compare(_toObj(head, vals[i]), _toObj(head, vals[best])) < 0) best = i;
  });
  // 1 escrita em lote p/ coluna toda (fora da categoria preserva o valor atual)
  const out = [];
  for (let i = 1; i < vals.length; i++) out.push([inCat[i] ? (i === best ? "TRUE" : "") : vals[i][ci]]);
  sh.getRange(2, ci + 1, vals.length - 1, 1).setValues(out);
  _clearSheetCache("Records");
}


// Outgoing repository port. No Apps Script object escapes this adapter.
function _table(name) {
  const sheet = _sheet(name);
  return {
    read: () => sheet.getDataRange().getValues(),
    remove: row => { sheet.deleteRow(row); _clearSheetCache(name); },
    range: (...args) => ({
      write: value => { sheet.getRange(...args).setValue(value); _clearSheetCache(name); },
      writeMany: values => { sheet.getRange(...args).setValues(values); _clearSheetCache(name); },
    }),
  };
}
const googleIdentity = {
  verify(idToken) {
    const response = UrlFetchApp.fetch("https://oauth2.googleapis.com/tokeninfo?id_token=" + encodeURIComponent(idToken), { muteHttpExceptions: true });
    return JSON.parse(response.getContentText());
  },
  exchangeCode(code, redirectUri) {
    const tokenResponse = UrlFetchApp.fetch("https://oauth2.googleapis.com/token", {
      method: "post",
      payload: {
        code,
        client_id: GOOGLE_CLIENT_ID,
        client_secret: GOOGLE_CLIENT_SECRET,
        redirect_uri: redirectUri,
        grant_type: "authorization_code",
      },
      muteHttpExceptions: true,
    });
    const tokens = JSON.parse(tokenResponse.getContentText());
    if (!tokens || !tokens.id_token) return null;
    return this.verify(tokens.id_token);
  }
};

// --- modules/identity/application/service.js ---
// Application service: all outgoing dependencies are injected by the composition root.
function createIdentityModule(ports) {
  const { GOOGLE_CLIENT_ID, GOOGLE_REDIRECT_ORIGINS, googleIdentity, ids, _append, _authUser, _clearFailedLogins, _effPoints, _findUserByEmail, _findUserById, _hash, _isAdmin, _loginBlocked, _newSession, _page, _publicUser, _recalcBest, _registerFailedLogin, _rows, _table, _toObj, _youtubeOk } = ports;
  const respond = value => value;
  const passwordOk = pass => pass.length >= 8 && /[A-Z]/.test(pass) && /[A-Za-z]/.test(pass) && /\d/.test(pass) && /[^A-Za-z0-9\s]/.test(pass);
  const nicknameTaken = (nickname, exceptId) => {
    const { header, rows } = _rows("Users");
    const target = String(nickname || "").toLowerCase();
    return rows.some(r => {
      const user = _toObj(header, r);
      return String(user.id) !== String(exceptId || "") && String(user.nickname || "").toLowerCase() === target;
    });
  };
  return function execute(action, e, payload = {}) {
  if (action === "getUser") {
    const u = _findUserById(e.parameter.id);
    if (!u) return respond({ erro: "Usuário não encontrado" });
    return respond(_publicUser(u));
  }
  if (action === "getMe") {
    const u = _authUser(e, null);
    if (!u) return respond({ erro: "Sessão inválida" });
    // E-mail só retorna ao titular autenticado: necessário para confirmar ações da conta.
    return respond({ ..._publicUser(u), email: u.email });
  }
  if (action === "listUsers") {
    if (!_isAdmin(e)) return respond({ erro: "Só admin" });
    const { header, rows } = _rows("Users");
    return respond(_page(rows.map(r => { const u = _toObj(header, r); return { id: u.id, nickname: u.nickname, email: u.email, role: u.role, status: u.status || "active", bio: u.bio || "", youtube_url: u.youtube_url || "", points: _effPoints(u), created_at: u.created_at }; }), e.parameter));
  }
  if (action === "listPendingUsers") {
    if (!_isAdmin(e)) return respond({ erro: "Só admin" });
    const { header, rows } = _rows("Users");
    const pending = rows.map(r => _toObj(header, r))
      .filter(user => String(user.status || "blocked") === "blocked")
      .sort((a, b) => String(b.created_at || "").localeCompare(String(a.created_at || "")))
      .map(user => ({ id: user.id, nickname: user.nickname, email: user.email, created_at: user.created_at, login_google: !!user.google_sub }));
    return respond(_page(pending, e.parameter));
  }
  if (action === "register") {
    const nickname = String(payload.nickname || "").trim();
    const email = String(payload.email || "").toLowerCase().trim();
    const pass = String(payload.password || "");
    if (!nickname || !email) return respond({ erro: "Dados inválidos" });
    if (!passwordOk(pass)) return respond({ erro: "Para proteger sua conta, use 8+ caracteres com letra maiúscula, número e símbolo" });
    if ([...nickname].length > 22) return respond({ erro: "Nickname até 22 caracteres" });
    if (nicknameTaken(nickname)) return respond({ erro: "Este nickname já está em uso." });
    const bio = String(payload.bio || "").trim();
    const youtube = String(payload.youtube_url || "").trim();
    if (youtube && !_youtubeOk(youtube)) return respond({ erro: "Link do canal deve ser do YouTube" });
    if (_findUserByEmail(email)) return respond({ erro: "Email já cadastrado" });
    const { header } = _rows("Users");
    const user = { id: ids.next(), nickname, email, pass_hash: _hash(pass), role: "user", status: "blocked", bio, youtube_url: youtube, created_at: new Date().toISOString() };
    _append("Users", user, header);
    return respond({ status: "ok", user: _publicUser(user) });
  }
  if (action === "login") {
    const email = String(payload.email || "").toLowerCase().trim();
    if (_loginBlocked(email)) return respond({ erro: "Muitas tentativas. Aguarde 5 minutos antes de tentar novamente." });
    const u = _findUserByEmail(email);
    if (!u || u.pass_hash !== _hash(String(payload.password || ""))) {
      _registerFailedLogin(email);
      return respond({ erro: "Login inválido" });
    }
    _clearFailedLogins(email);
    const token = _newSession(u.id);
    return respond({ status: "ok", token, user: _publicUser(u) });
  }
  if (action === "loginGoogle") {
    // O navegador recebe só um código de uso único. A troca e a validação do
    // ID token acontecem no Apps Script, que guarda o client secret.
    const code = String(payload.authorization_code || "");
    const redirectUri = String(payload.redirect_uri || "");
    if (!code) return respond({ erro: "Código do Google ausente" });
    if (!GOOGLE_REDIRECT_ORIGINS.includes(redirectUri)) return respond({ erro: "Origem do Google não autorizada" });
    let info;
    try {
      info = googleIdentity.exchangeCode(code, redirectUri);
    } catch (err) {
      return respond({ erro: "Falha ao validar Google" });
    }
    if (!info || info.aud !== GOOGLE_CLIENT_ID) return respond({ erro: "Google inválido" });
    if (info.email_verified !== "true" && info.email_verified !== true) return respond({ erro: "Email do Google não verificado" });
    if (new Date((Number(info.exp) || 0) * 1000) < new Date()) return respond({ erro: "Login expirado" });
    const email = String(info.email || "").toLowerCase().trim();
    const sub = String(info.sub || "");
    if (!email || !sub) return respond({ erro: "Google inválido" });
    const uh = _rows("Users");
    let found = null;
    uh.rows.forEach(r => {
      const x = _toObj(uh.header, r);
      if (!found && (String(x.google_sub || "") === sub || String(x.email).toLowerCase() === email)) found = x;
    });
    // A imagem vem da resposta já validada pelo Google, nunca do navegador.
    const avatarUrl = /^https:\/\/[^\s<>"'`]+$/i.test(String(info.picture || "")) ? String(info.picture) : "";
    const sh = _table("Users");
    const vals = sh.read();
    const head = vals[0];
    const ci = head.indexOf("google_sub");
    const avatarCol = head.indexOf("avatar_url");
    if (found) {
      // vincula o sub (conta cadastrada antes do Google entra pelo email verificado)
      for (let i = 1; i < vals.length; i++) {
        if (String(vals[i][0]) === String(found.id)) {
          if (ci >= 0 && !String(vals[i][ci] || "")) sh.range(i + 1, ci + 1).write(sub);
          if (avatarCol >= 0 && avatarUrl) sh.range(i + 1, avatarCol + 1).write(avatarUrl);
          break;
        }
      }
      if (avatarUrl) found.avatar_url = avatarUrl;
      const token = _newSession(found.id);
      return respond({ status: "ok", token, user: _publicUser(found) });
    }
    // conta nova via Google: bloqueada até o admin liberar (mesmo fluxo do register)
    // Usa a parte local do e-mail (antes do último @) como nickname inicial.
    // O e-mail já foi validado pelo Google; ainda limitamos o nome à regra do produto.
    const at = email.lastIndexOf("@");
    const nicknameBase = (at > 0 ? email.slice(0, at) : email).slice(0, 22) || "player";
    const nicknames = {};
    uh.rows.forEach(r => { const x = _toObj(uh.header, r); nicknames[String(x.nickname || "").toLowerCase()] = true; });
    let nick = nicknameBase;
    if (nicknames[nick.toLowerCase()]) {
      const numbered = nicknameBase.match(/^(.*?)(\d+)$/);
      const stem = numbered ? numbered[1] : nicknameBase;
      let next = numbered ? Number(numbered[2]) + 1 : 2;
      let attempts = 0;
      do {
        const suffix = String(next++);
        nick = (stem.slice(0, Math.max(1, 22 - suffix.length)) + suffix).slice(0, 22);
        attempts++;
      } while (nicknames[nick.toLowerCase()] && attempts < 10000);
      // Uma planilha com todas as 10 mil variações ocupadas é improvável; o
      // e-mail verificado é uma alternativa estável e única para esse caso.
      if (nicknames[nick.toLowerCase()]) nick = email;
    }
    const user = { id: ids.next(), nickname: nick, email, pass_hash: "", role: "user", status: "blocked", bio: "", youtube_url: "", avatar_url: avatarUrl, google_sub: sub, created_at: new Date().toISOString() };
    _append("Users", user, head);
    const token = _newSession(user.id);
    return respond({ status: "ok", token, user: _publicUser(user) });
  }
  if (action === "logout") {
    const sh = _table("Sessions");
    const vals = sh.read();
    for (let i = vals.length - 1; i >= 1; i--) {
      if (String(vals[i][0]) === String(payload.token)) sh.remove(i + 1);
    }
    return respond({ status: "ok" });
  }
  if (action === "updateMe") {
    const u = _authUser(e, payload);
    if (!u) return respond({ erro: "Sessão inválida" });
    const sh = _table("Users");
    const vals = sh.read();
    const head = vals[0];
    const iNick = head.indexOf("nickname");
    for (let i = 1; i < vals.length; i++) {
      if (String(vals[i][0]) === String(u.id)) {
        if (payload.nickname) {
          const nick = String(payload.nickname).trim();
          if (!nick) return respond({ erro: "Nickname inválido" });
          if ([...nick].length > 22) return respond({ erro: "Nickname até 22 caracteres" });
          if (nicknameTaken(nick, u.id)) return respond({ erro: "Este nickname já está em uso." });
          sh.range(i + 1, iNick + 1).write(nick);
        }
        if (payload.bio !== undefined) sh.range(i + 1, head.indexOf("bio") + 1).write(String(payload.bio));
        if (payload.youtube_url !== undefined) {
          const yt = String(payload.youtube_url).trim();
          if (yt && !_youtubeOk(yt)) return respond({ erro: "Link do canal deve ser do YouTube" });
          sh.range(i + 1, head.indexOf("youtube_url") + 1).write(yt);
        }
        break;
      }
    }
    return respond({ status: "ok" });
  }
  if (action === "changePassword") {
    const u = _authUser(e, payload);
    if (!u) return respond({ erro: "Sessão inválida" });
    if (String(u.pass_hash || "") && u.pass_hash !== _hash(String(payload.current_password || ""))) return respond({ erro: "A senha atual não confere." });
    const next = String(payload.new_password || "");
    if (!passwordOk(next)) return respond({ erro: "Para proteger sua conta, use 8+ caracteres com letra maiúscula, número e símbolo" });
    const sh = _table("Users"), vals = sh.read(), head = vals[0], passCol = head.indexOf("pass_hash");
    for (let i = 1; i < vals.length; i++) if (String(vals[i][0]) === String(u.id)) sh.range(i + 1, passCol + 1).write(_hash(next));
    return respond({ status: "ok" });
  }
  if (action === "deleteMe") {
    const u = _authUser(e, payload);
    if (!u) return respond({ erro: "Sessão inválida" });
    if (String(payload.email || "").toLowerCase().trim() !== String(u.email || "").toLowerCase().trim()) return respond({ erro: "Informe o e-mail desta conta para confirmar." });
    if (!String(u.pass_hash || "")) return respond({ erro: "Defina uma senha antes de excluir uma conta vinculada ao Google." });
    if (u.pass_hash !== _hash(String(payload.password || ""))) return respond({ erro: "A senha não confere." });
    const records = _table("Records"), recordVals = records.read(), recordHead = recordVals[0] || [];
    const categories = {};
    const deletedRecordIds = {};
    for (let i = recordVals.length - 1; i >= 1; i--) {
      const row = recordVals[i];
      if (String(row[recordHead.indexOf("user_id")]) === String(u.id)) {
        deletedRecordIds[String(row[recordHead.indexOf("id")])] = true;
        const key = [row[recordHead.indexOf("course_id")], row[recordHead.indexOf("powerband_id")], row[recordHead.indexOf("method")] || "com_ajuda", row[recordHead.indexOf("wind")] || "normal"].map(String);
        categories[key.join("|")] = key;
        records.remove(i + 1);
      }
    }
    const votes = _table("Votes"), voteVals = votes.read(), voteHead = voteVals[0] || [];
    for (let i = voteVals.length - 1; i >= 1; i--) if (String(voteVals[i][voteHead.indexOf("user_id")]) === String(u.id) || deletedRecordIds[String(voteVals[i][voteHead.indexOf("record_id")])]) votes.remove(i + 1);
    const sessions = _table("Sessions"), sessionVals = sessions.read();
    for (let i = sessionVals.length - 1; i >= 1; i--) if (String(sessionVals[i][1]) === String(u.id)) sessions.remove(i + 1);
    const users = _table("Users"), userVals = users.read();
    for (let i = userVals.length - 1; i >= 1; i--) if (String(userVals[i][0]) === String(u.id)) users.remove(i + 1);
    Object.values(categories).forEach(c => _recalcBest(c[0], c[1], c[2], c[3]));
    return respond({ status: "ok" });
  }
  if (action === "setUserStatus") {
    // admin libera (active) ou bloqueia (blocked) conta p/ envio de records
    const u = _authUser(e, payload);
    if (!u || u.role !== "admin") return respond({ erro: "Só admin" });
    if (!["active", "blocked"].includes(payload.status)) return respond({ erro: "status inválido" });
    if (String(payload.id) === String(u.id)) return respond({ erro: "Não altere a própria conta" });
    const sh = _table("Users");
    const vals = sh.read();
    const head = vals[0];
    for (let i = 1; i < vals.length; i++) {
      if (String(vals[i][0]) === String(payload.id)) {
        sh.range(i + 1, head.indexOf("status") + 1).write(payload.status);
        return respond({ status: "ok" });
      }
    }
    return respond({ erro: "Usuário não encontrado" });
  }
  if (action === "adminResetPassword") {
    const admin = _authUser(e, payload);
    if (!admin || admin.role !== "admin") return respond({ erro: "Só admin" });
    const target = _findUserById(payload.id);
    if (!target) return respond({ erro: "Usuário não encontrado" });
    if (String(target.id) === String(admin.id)) return respond({ erro: "Use a aba Segurança para alterar sua própria senha." });
    const next = String(payload.new_password || "");
    if (!passwordOk(next)) return respond({ erro: "Para proteger a conta, use 8+ caracteres com letra maiúscula, número e símbolo" });
    const users = _table("Users"), userVals = users.read(), userHead = userVals[0] || [], passCol = userHead.indexOf("pass_hash");
    for (let i = 1; i < userVals.length; i++) if (String(userVals[i][0]) === String(target.id)) users.range(i + 1, passCol + 1).write(_hash(next));
    // A senha anterior deixa de valer imediatamente em todos os dispositivos.
    const sessions = _table("Sessions"), sessionVals = sessions.read();
    for (let i = sessionVals.length - 1; i >= 1; i--) if (String(sessionVals[i][1]) === String(target.id)) sessions.remove(i + 1);
    return respond({ status: "ok" });
  }
    throw new Error("Unsupported identity action: " + action);
  };
}

// --- modules/catalog/application/service.js ---
// Application service: all outgoing dependencies are injected by the composition root.
function createCatalogModule(ports) {
  const { ids, _append, _authUser, _isAdmin, _recalcBest, _rows, _table, _toObj } = ports;
  const respond = value => value;
  return function execute(action, e, payload = {}) {
  if (action === "listCourses") {
    const { header, rows } = _rows("Courses");
    const all = rows.map(r => _toObj(header, r));
    if (e.parameter.include_inactive === "1" && _isAdmin(e)) return respond(all);
    return respond(all.filter(c => String(c.active).toUpperCase() === "TRUE"));
  }
  if (action === "listBands") {
    const { header, rows } = _rows("PowerBands");
    const all = rows.map(r => _toObj(header, r));
    all.sort((a, b) => Number(a.min) - Number(b.min));
    if (e.parameter.include_inactive === "1" && _isAdmin(e)) return respond(all);
    return respond(all.filter(b => String(b.active).toUpperCase() === "TRUE"));
  }
  if (action === "upsertBand" || action === "upsertCourse") {
    const u = _authUser(e, payload);
    if (!u || u.role !== "admin") return respond({ erro: "Só admin" });
    const sheetName = action === "upsertBand" ? "PowerBands" : "Courses";
    const nameKey = action === "upsertBand" ? "label" : "name";
    const norm = (s) => String(s == null ? "" : s).trim().toLowerCase();
    const sh = _table(sheetName);
    const vals = sh.read();
    const head = vals[0];
    const nameCol = head.indexOf(nameKey);
    if (payload.data && payload.data[nameKey] != null) payload.data[nameKey] = String(payload.data[nameKey]).trim();
    for (let i = 1; i < vals.length; i++) {
      if (String(vals[i][0]) === String(payload.id)) {
        // EDIT por id: não deixa renomear p/ nome de OUTRO
        const newName = payload.data && payload.data[nameKey] != null ? norm(payload.data[nameKey]) : "";
        if (newName) {
          for (let j = 1; j < vals.length; j++) {
            if (j !== i && norm(vals[j][nameCol]) === newName) return respond({ erro: "Nome já existe" });
          }
        }
        Object.keys(payload.data || {}).forEach(k => {
          const c = head.indexOf(k);
          if (c >= 0) sh.range(i + 1, c + 1).write(payload.data[k]);
        });
        return respond({ status: "ok", updated: true });
      }
    }
    // ADD idempotente por nome: duplo clique / retry / lentidão não duplica
    if (payload.data && payload.data[nameKey] != null) {
      const nn = norm(payload.data[nameKey]);
      for (let i = 1; i < vals.length; i++) {
        if (nn && norm(vals[i][nameCol]) === nn) return respond({ status: "ok", id: String(vals[i][0]), deduped: true });
      }
    }
    const row = Object.assign({ id: payload.id || ids.next() }, payload.data);
    _append(sheetName, row, head); // head já lido acima: sem releitura
    return respond({ status: "ok", id: row.id });
  }
  if (action === "deleteBand" || action === "deleteCourse") {
    const u = _authUser(e, payload);
    if (!u || u.role !== "admin") return respond({ erro: "Só admin" });
    if (action === "deleteCourse") {
      const rh = _rows("Records");
      if (rh.rows.some(r => String(_toObj(rh.header, r).course_id) === String(payload.id))) {
        return respond({ erro: "Em uso por records — desative em vez de excluir" });
      }
    } else {
      // deleteBand: records da faixa são realocados p/ outra faixa ativa que englobe a força
      const bh = _rows("PowerBands");
      const bands = bh.rows.map(r => _toObj(bh.header, r));
      const sh = _table("Records");
      const vals = sh.read();
      const head = vals[0];
      const moves = [];
      for (let i = 1; i < vals.length; i++) {
        if (String(vals[i][head.indexOf("powerband_id")]) !== String(payload.id)) continue;
        const pv = Number(vals[i][head.indexOf("power_value")]);
        const other = bands.find(b => String(b.id) !== String(payload.id) && String(b.active).toUpperCase() === "TRUE" && pv >= Number(b.min) && pv <= Number(b.max));
        if (!other) return respond({ erro: "Força " + pv + " não cabe em outra faixa ativa — crie uma que englobe antes" });
        moves.push({ row: i + 1, band: String(other.id) });
      }
      moves.forEach(m => sh.range(m.row, head.indexOf("powerband_id") + 1).write(m.band));
      const cats = {};
      moves.forEach(m => {
        const r = _toObj(head, vals[m.row - 1]); // vals já em memória: sem releitura por move
        const mt = String(r.method || "com_ajuda"), wd = String(r.wind || "normal");
        cats[String(r.course_id) + "|" + String(payload.id) + "|" + mt + "|" + wd] = [String(r.course_id), String(payload.id), mt, wd];
        cats[String(r.course_id) + "|" + m.band + "|" + mt + "|" + wd] = [String(r.course_id), m.band, mt, wd];
      });
      Object.values(cats).forEach(([c, b, mt, wd]) => _recalcBest(c, b, mt, wd));
      const bsh = _table("PowerBands");
      const bvals = bsh.read();
      for (let i = 1; i < bvals.length; i++) {
        if (String(bvals[i][0]) === String(payload.id)) { bsh.remove(i + 1); return respond({ status: "ok", realocados: moves.length }); }
      }
      return respond({ erro: "Não encontrado" });
    }
    const sh = _table("Courses");
    const vals = sh.read();
    for (let i = 1; i < vals.length; i++) {
      if (String(vals[i][0]) === String(payload.id)) { sh.remove(i + 1); return respond({ status: "ok" }); }
    }
    return respond({ erro: "Não encontrado" });
  }
    throw new Error("Unsupported catalog action: " + action);
  };
}

// --- modules/records/application/service.js ---
// Application service: all outgoing dependencies are injected by the composition root.
function createRecordsModule(ports) {
  const { METHODS, PTS_ADMIN_OK, PTS_IMPROVE_ADMIN, RecordPolicy, RecordDraft, ids, WINDS, _addPoints, _append, _authUser, _bandForPower, _isLiveRow, _makeProposal, _page, _recalcBest, _rows, _table, _toObj, _urlOk } = ports;
  const respond = value => value;
  return function execute(action, e, payload = {}) {
  if (action === "listRecords") {
    // filtros públicos: course_id, powerband_id, nickname, status default=approved
    // resposta inclui `nickname` do dono p/ linkar o perfil
    // não-approved (pending/rejected/all) só dono ou admin
    const p = e.parameter;
    const status = p.status || "approved";
    if (status !== "approved") {
      const me = _authUser(e, null);
      const mine = p.user_id && me && String(me.id) === String(p.user_id);
      if (!mine && !(me && me.role === "admin")) return respond({ erro: "Só dono ou admin" });
    }
    const { header, rows } = _rows("Records");
    const uh = _rows("Users");
    const users = {};
    uh.rows.forEach(r => { const u = _toObj(uh.header, r); users[String(u.id)] = u; });
    let recs = rows.map(r => _toObj(header, r));
    if (status !== "all") recs = recs.filter(x => String(x.status) === status);
    if (p.community === "1" || p.community === "0" || p.community === "-1") recs = recs.filter(x => Number(x.community || 0) === Number(p.community));
    // Sheets converte "TRUE" para booleano em algumas planilhas. Trate os dois
    // formatos para que o BEST não suma do ranking em produção.
    if (p.best === "1") recs = recs.filter(x => String(x.is_best).toUpperCase() === "TRUE");
    if (p.proposal === "1") recs = recs.filter(x => String(x.edit_of || "") !== "");
    if (p.edited === "1") recs = recs.filter(x => x.edited === "TRUE" && !x.edit_of);
    if (p.course_id) recs = recs.filter(x => String(x.course_id) === String(p.course_id));
    if (p.powerband_id) recs = recs.filter(x => String(x.powerband_id) === String(p.powerband_id));
    if (p.method) recs = recs.filter(x => String(x.method || "com_ajuda") === String(p.method));
    if (p.wind) recs = recs.filter(x => String(x.wind || "normal") === String(p.wind));
    if (p.user_id) recs = recs.filter(x => String(x.user_id) === String(p.user_id));
    if (p.nickname) {
      const q = String(p.nickname).toLowerCase();
      recs = recs.filter(x => String((users[String(x.user_id)] || {}).nickname || "").toLowerCase().includes(q));
    }
    // melhor score primeiro
    recs.sort(RecordPolicy.compare);
    const mapped = recs.map(x => Object.assign({}, x, { nickname: String((users[String(x.user_id)] || {}).nickname || "") }));
    return respond(_page(mapped, p));
  }
  if (action === "listPending") {
    const u = _authUser(e, null);
    if (!u || u.role !== "admin") return respond({ erro: "Só admin" });
    const { header, rows } = _rows("Records");
    const uh = _rows("Users");
    const names = {};
    uh.rows.forEach(r => { const x = _toObj(uh.header, r); names[String(x.id)] = String(x.nickname || ""); });
    return respond(_page(rows.map(r => _toObj(header, r)).filter(x => String(x.status) === "pending")
      .map(x => Object.assign({}, x, { nickname: names[String(x.user_id)] || "" })), e.parameter));
  }
  if (action === "submitRecord") {
    const u = _authUser(e, payload);
    if (!u) return respond({ erro: "Faça login" });
    if ((u.status || "active") !== "active") return respond({ erro: "Conta bloqueada — aguarde liberação do admin" });
    let draft;
    try { draft = RecordDraft(payload); } catch (error) { return respond({ erro: error.message }); }
    const { method, wind } = draft;
    const power = draft.power_value;
    const courseId = draft.course_id;
    const courses = _rows("Courses");
    if (!courses.rows.some(row => { const course = _toObj(courses.header, row); return String(course.id) === courseId && String(course.active).toUpperCase() === "TRUE"; })) return respond({ erro: "Campo não encontrado ou desativado" });
    const band = payload.powerband_id
      ? (() => { const { header, rows } = _rows("PowerBands"); for (const r of rows) { const b = _toObj(header, r); if (String(b.id) === String(payload.powerband_id)) return b; } return null; })()
      : _bandForPower(power);
    if (!band) return respond({ erro: "Faixa de força não encontrada p/ power_value=" + power });
    if (String(band.active).toUpperCase() !== "TRUE") return respond({ erro: "Faixa desativada" });
    const sh = _table("Records");
    const vals = sh.read();
    const head = vals[0];
    const col = n => head.indexOf(n) + 1;
    const FIELDS = ["course_id", "powerband_id", "power_value", "score", "pang", "method", "wind", "screenshot_url", "video_url"];
    const data = { course_id: courseId, powerband_id: String(band.id), power_value: power, score: Number(payload.score), pang: Number(payload.pang || 0), method, wind, screenshot_url: String(payload.screenshot_url || ""), video_url: String(payload.video_url || "") };
    // (user, course, força, método) identificam o record.
    // live (approved+comunidade) não é tocado: melhoria vira proposta ligada.
    const hi = n => head.indexOf(n);
    const same = [];
    vals.forEach((r, i) => {
      if (i > 0 && String(r[hi("user_id")]) === String(u.id) && String(r[hi("course_id")]) === courseId && Number(r[hi("power_value")]) === power && String(r[hi("method")] || "com_ajuda") === method && String(r[hi("wind")] || "normal") === wind) same.push(i);
    });
    const pendProp = same.find(i => String(vals[i][hi("status")]) === "pending" && String(vals[i][hi("edit_of")] || "") !== "");
    const clearPending = (idx) => {
      FIELDS.forEach(k => sh.range(idx + 1, col(k)).write(data[k]));
      sh.range(idx + 1, col("status")).write("pending");
      sh.range(idx + 1, col("validated_by")).write("");
      sh.range(idx + 1, col("validated_at")).write("");
      if (col("is_best") > 0) sh.range(idx + 1, col("is_best")).write("");
      if (col("edited") > 0) sh.range(idx + 1, col("edited")).write("TRUE");
      if (col("community") > 0) sh.range(idx + 1, col("community")).write("0");
      const votes = _table("Votes");
      const previous = votes.read();
      for (let i = previous.length - 1; i > 0; i--) {
        if (String(previous[i][previous[0].indexOf("record_id")]) === String(vals[idx][hi("id")])) votes.remove(i + 1);
      }
    };
    if (pendProp !== undefined) {
      clearPending(pendProp);
      _recalcBest(courseId, String(band.id), method, wind);
      return respond({ status: "ok", id: String(vals[pendProp][hi("id")]), updated: true });
    }
    if (same.some(i => _isLiveRow(head, vals[i]))) {
      const liveIdx = same.find(i => _isLiveRow(head, vals[i]));
      const id = _makeProposal(sh, head, col, liveIdx, vals, u, data);
      return respond({ status: "ok", id, proposal: true });
    }
    const dup = same[0];
    if (dup !== undefined) {
      clearPending(dup);
      _recalcBest(courseId, String(band.id), method, wind);
      return respond({ status: "ok", id: String(vals[dup][hi("id")]), updated: true });
    }
    const rec = Object.assign({ id: ids.next(), user_id: u.id, status: "pending", submitted_at: new Date().toISOString(), validated_by: "", validated_at: "", note: "" }, data);
    _append("Records", rec, head); // head já lido acima: sem releitura
    return respond({ status: "ok", id: rec.id });
  }
  if (action === "validateRecord") {
    // admin aprova/rejeita e pode REALOCAR course_id / powerband_id
    const u = _authUser(e, payload);
    if (!u || u.role !== "admin") return respond({ erro: "Só admin" });
    if (!["approved", "rejected"].includes(payload.status)) return respond({ erro: "status inválido" });
    const sh = _table("Records");
    const vals = sh.read();
    const head = vals[0];
    const col = n => head.indexOf(n) + 1;
    for (let i = 1; i < vals.length; i++) {
      if (String(vals[i][head.indexOf("id")]) === String(payload.id)) {
        const oldCourse = String(vals[i][head.indexOf("course_id")]);
        const oldBand = String(vals[i][head.indexOf("powerband_id")]);
        const oldMethod = String(vals[i][head.indexOf("method")] || "com_ajuda");
        const oldWind = String(vals[i][head.indexOf("wind")] || "normal");
        const origEditOf = String(vals[i][head.indexOf("edit_of")] || "");
        if (payload.method && !METHODS.includes(payload.method)) return respond({ erro: "método inválido" });
        if (payload.wind && !WINDS.includes(payload.wind)) return respond({ erro: "vento inválido" });
        const newMethod = String(payload.method || oldMethod);
        const newWind = String(payload.wind || oldWind);
        const requestedCommunity = ["-1", "0", "1"].includes(String(payload.community ?? "")) ? String(payload.community) : null;
        // "Approved by community" is a final publication state. Keeping a
        // pending/rejected status here made the row invisible to BEST despite
        // the admin explicitly publishing it through the manual form.
        const finalStatus = requestedCommunity === "1" ? "approved" : payload.status;
        sh.range(i + 1, col("status")).write(finalStatus); // approved|rejected
        if (col("is_best") > 0) sh.range(i + 1, col("is_best")).write(""); // recalc abaixo re-marca se for best
        if (payload.course_id) sh.range(i + 1, col("course_id")).write(String(payload.course_id));
        if (payload.powerband_id) sh.range(i + 1, col("powerband_id")).write(String(payload.powerband_id));
        if (payload.method && col("method") > 0) sh.range(i + 1, col("method")).write(newMethod);
        if (payload.wind && col("wind") > 0) sh.range(i + 1, col("wind")).write(newWind);
        if (payload.community_ok === true && col("community") > 0) sh.range(i + 1, col("community")).write("1"); // admin força ok da comunidade
        if (requestedCommunity && col("community") > 0) sh.range(i + 1, col("community")).write(requestedCommunity); // admin define: reprovado / não votado / aprovado
        sh.range(i + 1, col("validated_by")).write(u.nickname);
        sh.range(i + 1, col("validated_at")).write(new Date().toISOString());
        sh.range(i + 1, col("note")).write(String(payload.note || ""));
        if (finalStatus === "approved" && col("pts_admin") > 0 && String(vals[i][head.indexOf("pts_admin")]) !== "TRUE") {
          sh.range(i + 1, col("pts_admin")).write("TRUE");
          _addPoints(String(vals[i][head.indexOf("user_id")]), origEditOf ? PTS_IMPROVE_ADMIN : PTS_ADMIN_OK);
        }
        if (finalStatus === "approved" && origEditOf) {
          // Aprovação FINAL da proposta (voltou da comunidade): aplica no original e apaga.
          // Na primeira aprovação vai p/ votação da comunidade como record normal.
          const postCom = payload.community_ok === true || requestedCommunity === "1" ? "1" : String(vals[i][head.indexOf("community")] || "0");
          if (postCom !== "1") {
            _recalcBest(oldCourse, oldBand, oldMethod, oldWind);
            _recalcBest(String(payload.course_id || oldCourse), String(payload.powerband_id || oldBand), newMethod, newWind);
            return respond({ status: "ok" });
          }
          // Aprovação final da proposta: aplica no original e apaga a proposta.
          // vals já tem tudo (original não foi tocado); proposta = vals[i] + overrides gravados acima.
          const oi = vals.findIndex((r, k) => k > 0 && String(r[head.indexOf("id")]) === origEditOf);
          if (oi > 0) {
            const ocat = [String(vals[oi][head.indexOf("course_id")]), String(vals[oi][head.indexOf("powerband_id")]), String(vals[oi][head.indexOf("method")] || "com_ajuda"), String(vals[oi][head.indexOf("wind")] || "normal")];
            const eff = _toObj(head, vals[i]);
            if (payload.course_id) eff.course_id = String(payload.course_id);
            if (payload.powerband_id) eff.powerband_id = String(payload.powerband_id);
            if (payload.method) eff.method = newMethod;
            if (payload.wind) eff.wind = newWind;
            eff.note = String(payload.note || "");
            ["course_id", "powerband_id", "power_value", "score", "pang", "method", "wind", "screenshot_url", "video_url", "note"].forEach(k => { if (col(k) > 0) sh.range(oi + 1, col(k)).write(eff[k]); });
            sh.remove(i + 1);
            _recalcBest(oldCourse, oldBand, oldMethod, oldWind);
            _recalcBest(ocat[0], ocat[1], ocat[2], ocat[3]);
            _recalcBest(String(payload.course_id || oldCourse), String(payload.powerband_id || oldBand), newMethod, newWind);
            return respond({ status: "ok", merged: true });
          } else if (col("edit_of") > 0) {
            sh.range(i + 1, col("edit_of")).write(""); // original sumiu: vira record normal
          }
        }
        _recalcBest(oldCourse, oldBand, oldMethod, oldWind);
        _recalcBest(String(payload.course_id || oldCourse), String(payload.powerband_id || oldBand), newMethod, newWind);
        return respond({ status: "ok" });
      }
    }
    return respond({ erro: "Record não encontrado" });
  }
  if (action === "updateRecord") {
    // Dono edita o próprio record (volta p/ pending); admin edita qualquer um (mantém status).
    const u = _authUser(e, payload);
    if (!u) return respond({ erro: "Faça login" });
    const isAdmin = u.role === "admin";
    const data = payload.data || {};
    const sh = _table("Records");
    const vals = sh.read();
    const head = vals[0];
    const col = n => head.indexOf(n) + 1;
    const ri = vals.findIndex((r, i) => i > 0 && String(r[head.indexOf("id")]) === String(payload.id));
    if (ri < 0) return respond({ erro: "Record não encontrado" });
    const rec = _toObj(head, vals[ri]);
    const isOwner = String(rec.user_id) === String(u.id);
    if (!isOwner && !isAdmin) return respond({ erro: "Só o dono pode editar" });
    if ((u.status || "active") !== "active") return respond({ erro: "Conta bloqueada — aguarde liberação do admin" });
    // Gerenciar manda direct:true (só vale p/ admin). Fora dele, até o admin
    // que é dono usa as mesmas permissões de jogador e entra na revisão.
    const direct = isAdmin && payload.direct === true;
    const ownerFields = ["score", "pang", "screenshot_url", "video_url"];
    if (isOwner && !direct && Object.keys(data).some(key => !ownerFields.includes(key))) {
      return respond({ erro: "Você só pode editar score, pang, vídeo e print. As demais informações são definidas na revisão." });
    }
    // Validate the complete proposed version before any persistence operation.
    try { RecordDraft(Object.assign({}, rec, data)); } catch (error) { return respond({ erro: error.message }); }
    if (data.course_id !== undefined) {
      const courses = _rows("Courses");
      if (!courses.rows.some(row => { const course = _toObj(courses.header, row); return String(course.id) === String(data.course_id) && String(course.active).toUpperCase() === "TRUE"; })) return respond({ erro: "Campo não encontrado ou desativado" });
    }
    let resolvedBand = null;
    if (data.powerband_id) {
      const bands = _rows("PowerBands");
      resolvedBand = bands.rows.map(row => _toObj(bands.header, row)).find(band => String(band.id) === String(data.powerband_id));
    } else if (data.power_value !== undefined) resolvedBand = _bandForPower(Number(data.power_value));
    if ((data.powerband_id || data.power_value !== undefined) && !resolvedBand) return respond({ erro: "Faixa de força não encontrada p/ power_value=" + data.power_value });
    if (resolvedBand && String(resolvedBand.active).toUpperCase() !== "TRUE") return respond({ erro: "Faixa desativada" });
    // Pelo Meus records todo mundo (inclusive admin) segue a regra comum: live vira proposta.
    if (isOwner && !direct && _isLiveRow(head, vals[ri])) {
      // Dono melhorando o próprio record live (mesmo sendo admin): vira proposta,
      // original segue valendo. Só admin editando record DE TERCEIROS altera direto.
      if (data.power_value !== undefined && data.powerband_id === undefined) {
        const band = _bandForPower(Number(data.power_value));
        if (!band) return respond({ erro: "Faixa de força não encontrada p/ power_value=" + data.power_value });
        data.powerband_id = String(band.id);
      }
      if (String(data.method || rec.method || "com_ajuda") === "sem_ajuda") {
        const v = data.video_url !== undefined ? String(data.video_url) : String(rec.video_url || "");
        if (!v.trim()) return respond({ erro: "Sem ajuda exige vídeo de prova" });
      }
      const scoreOrPangChanged = (data.score !== undefined && Number(data.score) !== Number(rec.score))
        || (data.pang !== undefined && Number(data.pang) !== Number(rec.pang || 0));
      // Proof-only updates go through the admin but retain the community
      // decision; score/Pang changes create a new community review.
      const id = _makeProposal(sh, head, col, ri, vals, u, data, !scoreOrPangChanged);
      return respond({ status: "ok", id, proposal: true, communityReview: scoreOrPangChanged });
    }
    const FIELDS = isOwner && !direct ? ownerFields : ["course_id", "power_value", "score", "pang", "screenshot_url", "video_url"];
    FIELDS.forEach(k => { if (data[k] !== undefined) sh.range(ri + 1, col(k)).write(data[k]); });
    if (data.wind !== undefined && col("wind") > 0) sh.range(ri + 1, col("wind")).write(String(data.wind));
    if (data.method !== undefined && col("method") > 0) sh.range(ri + 1, col("method")).write(String(data.method));
    if (!isAdmin) {
      const effMethod = String(data.method || rec.method || "com_ajuda");
      const effVideo = data.video_url !== undefined ? String(data.video_url) : String(rec.video_url || "");
      if (effMethod === "sem_ajuda" && !effVideo.trim()) return respond({ erro: "Sem ajuda exige vídeo de prova" });
    }
    if (isAdmin && data.note !== undefined) sh.range(ri + 1, col("note")).write(String(data.note));
    let newBandId = String(rec.powerband_id);
    if (data.powerband_id) {
      newBandId = String(data.powerband_id);
      sh.range(ri + 1, col("powerband_id")).write(newBandId);
    } else if (data.power_value !== undefined) {
      const band = _bandForPower(Number(data.power_value));
      if (!band) return respond({ erro: "Faixa de força não encontrada p/ power_value=" + data.power_value });
      newBandId = String(band.id);
      sh.range(ri + 1, col("powerband_id")).write(newBandId);
    }
    if (isOwner && !direct) {
      // Dono reenvia p/ fila (mesmo sendo admin); só Gerenciar (direct) mantém direto.
      sh.range(ri + 1, col("status")).write("pending");
      sh.range(ri + 1, col("validated_by")).write("");
      sh.range(ri + 1, col("validated_at")).write("");
      if (col("is_best") > 0) sh.range(ri + 1, col("is_best")).write("");
      { // Invalidate votes even while community is still undecided (0).
        // Dado mudou depois do voto: os votos valiam p/ outra versão — zera tudo e volta
        // p/ não votado. O admin revisa e a comunidade vota de novo no dado atual.
        // (Apelação sem editar não cai aqui: appealVote não altera dado.)
        if (col("community") > 0) sh.range(ri + 1, col("community")).write("0");
        const vs = _table("Votes");
        const vv = vs.read();
        const vhi = n => vv[0].indexOf(n);
        for (let i = vv.length - 1; i > 0; i--) {
          if (String(vv[i][vhi("record_id")]) === String(rec.id)) vs.remove(i + 1);
        }
      }
    }
    if (col("edited") > 0) sh.range(ri + 1, col("edited")).write("TRUE"); // reenviado após edição
    // categoria nova a partir da memória (rec + data): sem releitura da planilha
    const newCourse = String(data.course_id !== undefined ? data.course_id : rec.course_id);
    const newMethod = String(data.method !== undefined ? data.method : (rec.method || "com_ajuda"));
    const newWind = String(data.wind !== undefined ? data.wind : (rec.wind || "normal"));
    _recalcBest(String(rec.course_id), String(rec.powerband_id), String(rec.method || "com_ajuda"), String(rec.wind || "normal"));
    _recalcBest(newCourse, newBandId, newMethod, newWind);
    return respond({ status: "ok" });
  }
    throw new Error("Unsupported records action: " + action);
  };
}

// --- modules/community/application/service.js ---
// Application service: all outgoing dependencies are injected by the composition root.
function createCommunityModule(ports) {
  const { PTS_COM_OK, PTS_IMPROVE_COM, ids, VotingPolicy, _addPoints, _append, _authUser, _effPoints, _recalcBest, _rows, _table, _tally, _toObj } = ports;
  const respond = value => value;
  return function execute(action, e, payload = {}) {
  if (action === "tally") {
    return respond(_tally(e.parameter.id || ""));
  }
  if (action === "tallies") {
    // placares em lote: 1 leitura p/ até 30 ids (página da comunidade fazia 1 request por candidato)
    const ids = String(e.parameter.ids || "").split(",").map(s => s.trim()).filter(Boolean).slice(0, 30);
    const { header, rows } = _rows("Votes");
    const out = {};
    ids.forEach(id => { out[id] = { approve: 0, reject: 0, voters: 0 }; });
    const seen = {};
    rows.forEach(r => {
      const v = _toObj(header, r);
      const t = out[String(v.record_id)];
      if (!t) return;
      const key = String(v.record_id) + "|" + String(v.user_id);
      if (!seen[key]) { seen[key] = 1; t.voters++; }
      if (v.vote === "approve") t.approve += Number(v.weight || 0);
      else t.reject += Number(v.weight || 0);
    });
    return respond(out);
  }
  if (action === "myVotes") {
    const u = _authUser(e, null);
    if (!u) return respond({ erro: "Faça login" });
    const { header, rows } = _rows("Votes");
    const mine = {};
    rows.forEach(r => { const v = _toObj(header, r); if (String(v.user_id) === String(u.id)) mine[String(v.record_id)] = v.vote; });
    return respond(mine);
  }
  if (action === "vote") {
    const u = _authUser(e, payload);
    if (!u) return respond({ erro: "Faça login" });
    if ((u.status || "active") !== "active") return respond({ erro: "Conta bloqueada" });
    if (!["approve", "reject"].includes(payload.vote)) return respond({ erro: "voto inválido" });
    const rh = _rows("Records");
    const rec = rh.rows.map(r => _toObj(rh.header, r)).find(x => String(x.id) === String(payload.id));
    if (!rec) return respond({ erro: "Record não encontrado" });
    if (String(rec.status) !== "approved" || Number(rec.community || 0) !== 0) return respond({ erro: "Fora de votação" });
    if (String(rec.user_id) === String(u.id)) return respond({ erro: "Não vote no próprio record" });
    const w = _effPoints(u);
    if (w < 10) return respond({ erro: "Sem pontos suficientes (mínimo 10)" });
    // 1 voto por usuário/record (revotar atualiza), peso = pontos atuais
    const vsh = _table("Votes");
    const vv = vsh.read();
    const vh = vv[0];
    let found = false;
    for (let i = 1; i < vv.length; i++) {
      if (String(vv[i][vh.indexOf("record_id")]) === String(payload.id) && String(vv[i][vh.indexOf("user_id")]) === String(u.id)) {
        vsh.range(i + 1, vh.indexOf("vote") + 1).write(payload.vote);
        vsh.range(i + 1, vh.indexOf("weight") + 1).write(w);
        found = true;
        break;
      }
    }
    if (!found) {
      _append("Votes", { id: ids.next(), record_id: String(payload.id), user_id: u.id, vote: payload.vote, weight: w, created_at: new Date().toISOString() }, vh); // vh já lido acima
    }
    const t = _tally(payload.id);
    const decided = VotingPolicy.decide(t);
    if (decided) {
      const sh = _table("Records");
      const vals = sh.read();
      const head = vals[0];
      const col = n => head.indexOf(n) + 1;
      const ri = vals.findIndex((r, i) => i > 0 && String(r[head.indexOf("id")]) === String(payload.id));
      if (decided === "approved") {
        sh.range(ri + 1, col("status")).write("pending"); // volta p/ fila final do admin
        sh.range(ri + 1, col("validated_by")).write("");
        sh.range(ri + 1, col("validated_at")).write("");
        if (col("community") > 0) sh.range(ri + 1, col("community")).write("1");
        if (col("pts_com") > 0 && String(vals[ri][head.indexOf("pts_com")]) !== "TRUE") {
          sh.range(ri + 1, col("pts_com")).write("TRUE");
          const isProp = String(vals[ri][head.indexOf("edit_of")] || "") !== "";
          _addPoints(String(vals[ri][head.indexOf("user_id")]), isProp ? PTS_IMPROVE_COM : PTS_COM_OK);
        }
      } else {
        // Rejeitado pela comunidade: volta p/ fila do admin como pedido (pending + -1),
        // igual ao aprovado — palavra final é do admin (confirma, força ok ou reabre).
        sh.range(ri + 1, col("status")).write("pending");
        sh.range(ri + 1, col("validated_by")).write("");
        sh.range(ri + 1, col("validated_at")).write("");
        if (col("community") > 0) sh.range(ri + 1, col("community")).write("-1");
      }
      _recalcBest(String(vals[ri][head.indexOf("course_id")]), String(vals[ri][head.indexOf("powerband_id")]), String(vals[ri][head.indexOf("method")] || "com_ajuda"), String(vals[ri][head.indexOf("wind")] || "normal"));
    }
    return respond({ status: "ok", vote: payload.vote, tally: t, decided });
  }
  if (action === "appealVote") {
    // Dono pede reavaliação de rejeição confirmada (approved/-1) sem precisar editar nada:
    // volta p/ pending (fila do admin), comunidade segue -1, marca edited. Só sai do
    // pending pelo admin (confirma, força ok ou reabre). Sem spam: já na fila não apela.
    const u = _authUser(e, payload);
    if (!u) return respond({ erro: "Faça login" });
    const sh = _table("Records");
    const vals = sh.read();
    const head = vals[0];
    const col = n => head.indexOf(n) + 1;
    const ri = vals.findIndex((r, i) => i > 0 && String(r[head.indexOf("id")]) === String(payload.id));
    if (ri < 0) return respond({ erro: "Record não encontrado" });
    const rec = _toObj(head, vals[ri]);
    if (String(rec.user_id) !== String(u.id)) return respond({ erro: "Só o dono pode pedir" });
    if (String(rec.status) !== "approved" || Number(rec.community || 0) !== -1) return respond({ erro: "Só rejeição confirmada" });
    sh.range(ri + 1, col("status")).write("pending");
    if (col("edited") > 0) sh.range(ri + 1, col("edited")).write("TRUE");
    return respond({ status: "ok" });
  }
  if (action === "reopenVote") {
    // Admin reabre votação: rejeitado confirmado (-1, approved|pending) ou final pendente (1,
    // pending) voltam p/ approved/0 (fila da Comunidade) e os votos são apagados.
    // Record já publicado no index (approved/1) não reabre por aqui (usar o Gerenciar).
    // Rejeição/aprovação não pagam pontos aqui, então nada a estornar (pts_com só paga 1x).
    const u = _authUser(e, payload);
    if (!u || u.role !== "admin") return respond({ erro: "Só admin" });
    const sh = _table("Records");
    const vals = sh.read();
    const head = vals[0];
    const col = n => head.indexOf(n) + 1;
    const ri = vals.findIndex((r, i) => i > 0 && String(r[head.indexOf("id")]) === String(payload.id));
    if (ri < 0) return respond({ erro: "Record não encontrado" });
    const st = String(vals[ri][head.indexOf("status")]);
    const com = Number(vals[ri][head.indexOf("community")] || 0);
    const ok = (com === -1 && (st === "approved" || st === "pending")) || (com === 1 && st === "pending");
    if (!ok) return respond({ erro: "Só pedido pendente votado ou rejeitado confirmado" });
    sh.range(ri + 1, col("status")).write("approved");
    sh.range(ri + 1, col("community")).write("0");
    const vs = _table("Votes");
    const vv = vs.read();
    const vhi = n => vv[0].indexOf(n);
    for (let i = vv.length - 1; i > 0; i--) {
      if (String(vv[i][vhi("record_id")]) === String(payload.id)) vs.remove(i + 1);
    }
    return respond({ status: "ok" });
  }
    throw new Error("Unsupported community action: " + action);
  };
}

// --- composition.js ---
function createApplication() {
  const identity = createIdentityModule({ GOOGLE_CLIENT_ID, GOOGLE_REDIRECT_ORIGINS, googleIdentity, ids: { next: () => Utilities.getUuid() }, _append, _authUser, _clearFailedLogins, _effPoints, _findUserByEmail, _findUserById, _hash, _isAdmin, _loginBlocked, _newSession, _page, _publicUser, _recalcBest, _registerFailedLogin, _rows, _table, _toObj, _youtubeOk });
  const catalog = createCatalogModule({ ids: { next: () => Utilities.getUuid() }, _append, _authUser, _isAdmin, _recalcBest, _rows, _table, _toObj });
  const records = createRecordsModule({ METHODS, PTS_ADMIN_OK, PTS_IMPROVE_ADMIN, RecordPolicy, RecordDraft, ids: { next: () => Utilities.getUuid() }, WINDS, _addPoints, _append, _authUser, _bandForPower, _isLiveRow, _makeProposal, _page, _recalcBest, _rows, _table, _toObj, _urlOk });
  const community = createCommunityModule({ PTS_COM_OK, PTS_IMPROVE_COM, ids: { next: () => Utilities.getUuid() }, VotingPolicy, _addPoints, _append, _authUser, _effPoints, _recalcBest, _rows, _table, _tally, _toObj });
  return {
    get: { getUser: identity, getMe: identity, listUsers: identity, listPendingUsers: identity, listCourses: catalog, listBands: catalog, listRecords: records, listPending: records, tally: community, tallies: community, myVotes: community },
    post: { register: identity, login: identity, loginGoogle: identity, logout: identity, updateMe: identity, changePassword: identity, deleteMe: identity, setUserStatus: identity, adminResetPassword: identity, upsertBand: catalog, upsertCourse: catalog, deleteBand: catalog, deleteCourse: catalog, submitRecord: records, validateRecord: records, updateRecord: records, vote: community, appealVote: community, reopenVote: community },
  };
}

// --- adapters/http.js ---
// Driving adapter: protocol and serialization stay outside use cases.
function doGet(e) {
  const action = String(e.parameter.action || "").trim();
  const actions = createApplication().get;
  const handler = actions[action];
  return _out(Object.prototype.hasOwnProperty.call(actions, action) ? handler(action, e) : { erro: "action desconhecida: " + action });
}
function doPost(e) {
  const lock = LockService.getScriptLock();
  try { lock.waitLock(10000); } catch (err) { return _out({ erro: "Muita gente escrevendo junto — tente de novo" }); }
  try {
    let payload;
    try { payload = JSON.parse((e.postData && e.postData.contents) || "{}"); }
    catch (err) { return _out({ erro: "Requisição inválida" }); }
    if (!payload || typeof payload !== "object" || Array.isArray(payload)) return _out({ erro: "Requisição inválida" });
    const actions = createApplication().post;
    const action = String(payload.action || "");
    return _out(Object.prototype.hasOwnProperty.call(actions, action) ? actions[action](action, e, payload) : { erro: "action desconhecida: " + action });
  } finally { lock.releaseLock(); }
}
