// Suite local: executa o backend/Code.gs REAL contra os CSVs (editáveis no Calc).
// Uso: node tests/run.js   (fixtures temporárias isoladas, exit 1 se falhar)
const fs = require("node:fs");
const path = require("node:path");
const os = require("node:os");
const testFixtures = fs.mkdtempSync(path.join(os.tmpdir(), "pwr-tests-"));
process.env.PWR_FIXTURES_DIR = testFixtures;
process.on("exit", () => fs.rmSync(testFixtures, { recursive: true, force: true }));
require("./setup.js");
const { loadApi } = require("./gas-mock.js");

const ORIGEM = "TROQUE_ISSO_pwr_123";
let pass = 0, fail = 0;
function ok(cond, name, extra = "") {
  if (cond) { pass++; console.log(`  ok: ${name}`); }
  else { fail++; console.log(`  FALHOU: ${name} ${extra}`); }
}

const api = loadApi();
const G = (action, p = {}) => api.get({ origem: ORIGEM, action, ...p });
const P = (action, d = {}) => api.post({ origem: ORIGEM, action, ...d });

console.log("== origem / schema ==");
ok(api.get({ origem: "errada", action: "listBands" }).erro, "GET origem inválida bloqueia");
ok(api.post({ origem: "errada", action: "login" }).erro, "POST origem inválida bloqueia");
ok(Array.isArray(G("listBands")) && G("listBands").length === 4, "4 faixas ativas");
ok(G("listCourses").length === 2, "2 courses ativos");

console.log("== auth ==");
const strongPass = "Pangya1!";
const reg = P("register", { nickname: "Player1", email: "p1@test.com", password: strongPass });
ok(reg.status === "ok" && reg.user.status === "blocked", "register cria user bloqueado");
ok(P("register", { nickname: "X", email: "p1@test.com", password: strongPass }).erro, "register email duplicado bloqueia");
ok(P("register", { nickname: "player1", email: "nick-duplicado@test.com", password: strongPass }).erro, "register nickname duplicado bloqueia");
ok(P("register", { nickname: "Y", email: "y@test.com", password: "123" }).erro, "register senha curta bloqueia");
ok(P("register", { nickname: "Y", email: "weak@test.com", password: "pangya12" }).erro, "register exige maiúscula");
ok(P("register", { nickname: "Y", email: "weak2@test.com", password: "Pangya12" }).erro, "register exige caractere especial");
ok(P("register", { nickname: "a".repeat(23), email: "long@test.com", password: strongPass }).erro, "register nickname >22 bloqueia");
ok(P("register", { nickname: "😀".repeat(22), email: "uni@test.com", password: strongPass }).status === "ok", "register 22 codepoints unicode ok");
ok(P("register", { nickname: "Bio", email: "bio@test.com", password: strongPass, bio: "sou player", youtube_url: "https://youtube.com/@bio" }).status === "ok", "register com bio/youtube");
ok(P("register", { nickname: "Bad", email: "bad@test.com", password: strongPass, youtube_url: "https://twitch.tv/x" }).erro, "register bloqueia link não-youtube");
const login = P("login", { email: "p1@test.com", password: strongPass });
ok(login.status === "ok" && login.token, "login retorna token");
const userTok = login.token;
const userId = login.user.id;
ok(P("login", { email: "p1@test.com", password: "errada" }).erro, "login senha errada bloqueia");
for (let i = 0; i < 5; i++) P("login", { email: "tentativas@test.com", password: "errada" });
ok(P("login", { email: "tentativas@test.com", password: "errada" }).erro.includes("Muitas tentativas"), "login limita tentativas repetidas");
ok(G("getMe", { token: userTok }).nickname === "Player1", "getMe retorna user");
const adminLogin = P("login", { email: "admin@test.com", password: "admin123" });
ok(adminLogin.status === "ok", "login admin da fixture");
  const adminTok = adminLogin.token;
const idleLogin = P("login", { email: "bio@test.com", password: strongPass });
const sessionsPath = path.join(testFixtures, "Sessions.csv");
const sessionRows = fs.readFileSync(sessionsPath, "utf8").trim().split("\n").map(line => line.split(","));
const lastSeenCol = sessionRows[0].indexOf("last_seen_at");
sessionRows.find(row => row[0] === idleLogin.token)[lastSeenCol] = new Date(Date.now() - 31 * 60 * 1000).toISOString();
fs.writeFileSync(sessionsPath, sessionRows.map(row => row.join(",")).join("\n") + "\n");
const expiredSessionApi = loadApi();
ok(expiredSessionApi.get({ origem: ORIGEM, action: "getMe", token: idleLogin.token }).erro === "Sessão inválida", "sessão expira por inatividade");

console.log("== login Google ==");
const g1 = P("loginGoogle", { id_token: "ga" });
ok(g1.status === "ok" && g1.user.status === "blocked" && g1.token && g1.user.nickname === "ga" && g1.user.avatar_url === "https://lh3.googleusercontent.com/a/ga", "loginGoogle cria conta bloqueada com foto e nickname do e-mail");
const g2 = P("loginGoogle", { id_token: "ga" });
ok(g2.status === "ok" && g2.user.id === g1.user.id, "mesmo Google entra na mesma conta (sub)");
const greg = P("register", { nickname: "GNormal", email: "gc@test.com", password: strongPass });
const g3 = P("loginGoogle", { id_token: "gc" });
ok(g3.status === "ok" && g3.user.id === greg.user.id, "conta com email vincula pelo Google");
ok(P("loginGoogle", { id_token: "gc" }).user.id === greg.user.id, "vinculada entra pelo sub");
ok(P("loginGoogle", { id_token: "bad" }).erro, "Google inválido bloqueia");
ok(P("loginGoogle", {}).erro, "sem id_token bloqueia");
ok(P("loginGoogle", { id_token: "nick-conflict" }).user.nickname === "player2", "nickname Google já usado recebe próximo número");
ok(P("updateMe", { token: userTok, nickname: "PLAYER2" }).erro, "edição bloqueia nickname duplicado");
ok(P("changePassword", { token: g1.token, new_password: "SenhaGoogle1!" }).status === "ok", "conta Google define primeira senha sem senha atual");
ok(P("login", { email: "ga@test.com", password: "SenhaGoogle1!" }).status === "ok", "conta Google entra também com senha definida");
ok(P("updateMe", { token: userTok, nickname: "PlayerUm" }).status === "ok", "updateMe troca nickname");
ok(P("updateMe", { token: userTok, nickname: "b".repeat(23) }).erro, "updateMe nickname >22 bloqueia");
ok(P("updateMe", { token: userTok, bio: "novo info", youtube_url: "https://youtu.be/abc" }).status === "ok", "updateMe bio/youtube");
ok(P("updateMe", { token: userTok, youtube_url: "https://outro.com/x" }).erro, "updateMe bloqueia link não-youtube");
ok(G("getMe", { token: userTok }).youtube_url === "https://youtu.be/abc", "youtube salvo");

console.log("== liberação de conta ==");
ok(P("submitRecord", { token: userTok, course_id: "blue_water", power_value: 245, score: -25 }).erro, "submit bloqueado antes da liberação");
ok(G("listUsers", { token: userTok }).erro === "Só admin", "listUsers bloqueia user comum");
ok(G("listPendingUsers", { token: userTok }).erro === "Só admin", "lista de novos usuários bloqueia user comum");
const users = G("listUsers", { token: adminTok });
ok(users.some((x) => x.id === userId && x.status === "blocked"), "admin vê conta bloqueada");
ok(G("listPendingUsers", { token: adminTok }).some((x) => x.id === userId), "admin vê novo usuário aguardando liberação");
ok(P("setUserStatus", { token: userTok, id: userId, status: "active" }).erro === "Só admin", "setUserStatus bloqueia user comum");
ok(P("setUserStatus", { token: adminTok, id: "admin-1", status: "blocked" }).erro, "admin não altera a própria conta");
ok(P("setUserStatus", { token: adminTok, id: userId, status: "active" }).status === "ok", "admin libera conta");

console.log("== submitRecord ==");
ok(P("submitRecord", { course_id: "blue_water", power_value: 245, score: -25 }).erro, "submit sem login bloqueia");
const sub = P("submitRecord", { token: userTok, course_id: "blue_water", power_value: 245, score: -25, method: "sem_ajuda", wind: "normal", video_url: "https://youtu.be/x" });
ok(sub.status === "ok", "submit auto-detecta faixa");
  ok(P("submitRecord", { token: userTok, course_id: "blue_water", power_value: 999, score: -25, method: "com_ajuda" }).erro, "submit força fora da faixa bloqueia");
ok(P("submitRecord", { token: userTok, course_id: "blue_water", power_value: 246, score: -25, method: "com_ajuda", wind: "normal", video_url: "javascript:alert(1)" }).erro, "submit bloqueia video javascript:");
ok(P("submitRecord", { token: userTok, course_id: "blue_water", power_value: 246, score: -25, method: "com_ajuda", wind: "normal", video_url: "https://video-invalido.example/prova" }).erro, "submit bloqueia origem de vídeo fora da lista");
ok(P("submitRecord", { token: userTok, course_id: "blue_water", power_value: 246, score: -25, method: "com_ajuda", wind: "normal", screenshot_url: 'https://x.com/a"b' }).erro, "submit bloqueia print com aspas");
ok(P("updateRecord", { token: userTok, id: sub.id, data: { video_url: "data:text/html,x" } }).erro, "update bloqueia video data:");
ok(P("updateRecord", { token: userTok, id: sub.id, data: { video_url: "https://www.twitch.tv/videos/123" } }).status === "ok", "update aceita origem Twitch");
ok(G("listRecords").length === 0, "público não vê pending");
ok(G("listPending", { token: userTok }).erro === "Só admin", "listPending bloqueia user comum");
const pend = G("listPending", { token: adminTok });
ok(pend.length === 1 && pend[0].powerband_id === "b241_250", "pending com faixa auto 241-250");
ok(pend[0].nickname === "PlayerUm", "pending inclui nickname");

console.log("== validateRecord (realocação) ==");
ok(P("validateRecord", { token: userTok, id: sub.id, status: "approved" }).erro === "Só admin", "validate bloqueia user comum");
ok(P("validateRecord", { token: adminTok, id: sub.id, status: "approved", powerband_id: "b251_260", note: "realocado" }).status === "ok", "admin aprova e realoca faixa");
const pub = G("listRecords");
ok(pub.length === 1 && pub[0].powerband_id === "b251_260" && pub[0].note === "realocado", "público vê approved realocado");
ok(pub[0].nickname === "PlayerUm" && pub[0].user_id === userId, "listRecords inclui nickname p/ link do perfil");
ok(G("listRecords", { powerband_id: "b251_260" }).length === 1, "filtro por faixa");
ok(G("listRecords", { nickname: "playerum" }).length === 1, "busca por nickname");
ok(G("listRecords", { course_id: "blue_water" }).length === 1, "filtro por course");

console.log("== updateRecord ==");
ok(P("updateRecord", { token: userTok, id: "inexistente", data: { score: -26 } }).erro, "update record inexistente bloqueia");
ok(P("updateRecord", { token: userTok, id: sub.id, data: { method: "sem_ajuda" } }).erro, "dono não altera método");
ok(P("updateRecord", { token: userTok, id: sub.id, data: { score: -26 } }).status === "ok", "dono edita próprio record");
const mine = G("listRecords", { user_id: userId, status: "all", token: userTok });
ok(mine.length === 1 && mine[0].status === "pending" && mine[0].score === "-26", "edição do dono volta p/ pending");
ok(P("validateRecord", { token: adminTok, id: sub.id, status: "approved" }).status === "ok", "admin re-aprova");
ok(P("updateRecord", { token: adminTok, id: sub.id, data: { score: -27 } }).status === "ok", "admin edita approved");
const after = G("listRecords", { user_id: userId, status: "all", token: userTok });
ok(after[0].status === "approved" && after[0].score === "-27", "edição do admin mantém approved");

console.log("== upsert/delete admin ==");
ok(P("upsertBand", { token: userTok, data: { label: "x" } }).erro === "Só admin", "upsert bloqueia user comum");
ok(P("upsertBand", { token: adminTok, id: "b261_270", data: { label: "261-270" } }).updated === true, "upsert atualiza faixa");
ok(P("upsertCourse", { token: adminTok, data: { name: "Wiz Wiz", active: "TRUE" } }).id, "upsert cria course");
const dup1 = P("upsertCourse", { token: adminTok, data: { name: "Dup Course", active: "TRUE" } });
const dup2 = P("upsertCourse", { token: adminTok, data: { name: "  dup course ", active: "TRUE" } });
ok(dup1.id && dup2.id === dup1.id && dup2.deduped === true, "upsertCourse repetido (casa/espaço) retorna o mesmo id");
ok(P("upsertCourse", { token: adminTok, id: dup1.id, data: { name: "Wiz Wiz" } }).erro === "Nome já existe", "renomear course p/ nome existente bloqueia");
const nb = P("upsertBand", { token: adminTok, data: { label: "271-280", min: 271, max: 280, active: "TRUE" } });
ok(nb.id, "upsert cria faixa");
const dupb2 = P("upsertBand", { token: adminTok, data: { label: "  271-280 ", min: 271, max: 280, active: "TRUE" } });
ok(dupb2.id === nb.id && dupb2.deduped === true, "upsertBand repetido retorna o mesmo id");
ok(P("deleteBand", { token: userTok, id: nb.id }).erro === "Só admin", "delete bloqueia user comum");
ok(P("deleteBand", { token: adminTok, id: nb.id }).status === "ok", "delete remove faixa sem uso");
const delOld = P("deleteBand", { token: adminTok, id: "b251_260" });
ok(delOld.status === "ok" && delOld.realocados === 1, "delete faixa em uso realoca");
const nc2 = P("upsertCourse", { token: adminTok, data: { name: "Inativo", active: "FALSE" } });
ok(nc2.id && !G("listCourses").some((c) => c.id === nc2.id), "público não vê course inativo");
ok(G("listCourses", { token: adminTok, include_inactive: "1" }).some((c) => c.id === nc2.id), "admin lista inativos");
ok(P("deleteCourse", { token: adminTok, id: nc2.id }).status === "ok", "delete remove course sem uso");
ok(P("deleteCourse", { token: adminTok, id: "blue_water" }).erro, "delete course em uso bloqueia");

console.log("== submit upsert + delete com realocação ==");
const dup = P("submitRecord", { token: userTok, course_id: "blue_water", power_value: 245, score: -30, method: "sem_ajuda", wind: "normal", video_url: "https://youtu.be/x" });
ok(dup.updated === true && dup.id === sub.id, "submit course+força iguais atualiza");
const chk = G("listRecords", { user_id: userId, status: "all", token: userTok }).find((r) => r.id === sub.id);
ok(chk.status === "pending" && chk.score === "-30", "upsert volta p/ pending");
ok(chk.edited === "TRUE", "upsert marca editado");
const pg = P("submitRecord", { token: userTok, course_id: "blue_lagoon", power_value: 250, score: -20, pang: 12500, method: "com_ajuda", wind: "normal" });
ok(pg.status === "ok" && !pg.updated, "submit com pang cria");
ok(Number(G("listRecords", { user_id: userId, status: "all", token: userTok }).find((r) => r.id === pg.id).pang) === 12500, "pang salvo");
ok(P("updateRecord", { token: userTok, id: pg.id, data: { pang: 13000 } }).status === "ok", "update pang");
const nb2 = P("upsertBand", { token: adminTok, data: { label: "240-260", min: 240, max: 260, active: "TRUE" } });
ok(nb2.id, "cria faixa que engloba");
const del = P("deleteBand", { token: adminTok, id: "b241_250" });
ok(del.status === "ok" && del.realocados === 2, "delete realoca p/ faixa que engloba");
ok(G("listRecords", { user_id: userId, status: "all", token: userTok }).find((r) => r.id === sub.id).powerband_id === nb2.id, "record realocado");
const nb3 = P("upsertBand", { token: adminTok, data: { label: "200-210", min: 200, max: 210, active: "TRUE" } });
const s200 = P("submitRecord", { token: userTok, course_id: "blue_lagoon", power_value: 205, score: -10, method: "com_ajuda", wind: "normal" });
ok(s200.status === "ok", "submit em faixa isolada");
ok(P("deleteBand", { token: adminTok, id: nb3.id }).erro, "delete sem faixa que englobe bloqueia");

console.log("== melhor da categoria ==");
const wb = P("upsertBand", { token: adminTok, data: { label: "280-290", min: 280, max: 290, active: "TRUE" } });
const ra = P("submitRecord", { token: userTok, course_id: "blue_water", power_value: 281, score: -25, pang: 10000, method: "com_ajuda", wind: "normal" });
const rb = P("submitRecord", { token: userTok, course_id: "blue_water", power_value: 282, score: -25, pang: 15000, method: "com_ajuda", wind: "normal" });
P("validateRecord", { token: adminTok, id: ra.id, status: "approved" });
P("validateRecord", { token: adminTok, id: rb.id, status: "approved" });
const cat = (id) => G("listRecords", { user_id: userId, status: "all", token: userTok }).find((r) => r.id === id);
ok(cat(ra.id).is_best !== "TRUE" && cat(rb.id).is_best !== "TRUE", "só admin-ok não é best");
P("validateRecord", { token: adminTok, id: ra.id, status: "approved", community_ok: true });
ok(cat(ra.id).is_best === "TRUE", "forçar ok da comunidade marca best");
P("validateRecord", { token: adminTok, id: rb.id, status: "approved", community_ok: true });
ok(cat(rb.id).is_best === "TRUE" && cat(ra.id).is_best !== "TRUE", "empate de score: maior pang é best");
ok(P("validateRecord", { token: adminTok, id: rb.id, status: "rejected", community: "1" }).status === "ok", "admin aprova comunidade manualmente");
ok(cat(rb.id).status === "approved" && Number(cat(rb.id).community) === 1 && cat(rb.id).is_best === "TRUE", "aprovação manual publica e recalcula BEST");
P("updateRecord", { token: adminTok, id: rb.id, data: { score: -20 } });
ok(cat(ra.id).is_best === "TRUE" && cat(rb.id).is_best !== "TRUE", "edição do admin preserva melhor da categoria");
P("updateRecord", { token: adminTok, id: ra.id, data: { note: "recorde insano" } });
ok(cat(ra.id).note === "recorde insano" && cat(ra.id).status === "approved", "nota do admin salva sem trocar status");
P("validateRecord", { token: adminTok, id: rb.id, status: "rejected" });
ok(cat(rb.id).is_best !== "TRUE" && cat(ra.id).is_best === "TRUE", "rejeitado perde a flag");
const mins = G("listBands").map((b) => Number(b.min));
ok(mins.length > 1 && mins.every((v, i) => i === 0 || v >= mins[i - 1]), "faixas ordenadas por min");
ok(G("listBands")[0].label === "200-210", "menor faixa primeiro");

console.log("== privacidade de não-approved ==");
ok(G("listRecords", { user_id: userId, status: "pending" }).erro, "anônimo não vê pending alheio");
P("register", { nickname: "Outro", email: "outro@test.com", password: strongPass });
const tok2 = P("login", { email: "outro@test.com", password: strongPass }).token;
ok(G("listRecords", { user_id: userId, status: "pending", token: tok2 }).erro, "outro user não vê pending alheio");
ok(G("listRecords", { user_id: userId, status: "pending", token: userTok }).length === 3, "dono vê próprios pendings");
ok(G("listRecords", { status: "all", token: adminTok }).length === 5, "admin vê tudo");

console.log("== paginação ==");
const pg1 = G("listRecords", { status: "all", token: adminTok, limit: "2", offset: "0" });
ok(pg1.total === 5 && pg1.rows.length === 2, "listRecords pagina com total");
const pg2 = G("listRecords", { status: "all", token: adminTok, limit: "2", offset: "2" });
ok(pg2.rows.length === 2 && pg2.rows[0].id !== pg1.rows[0].id, "offset avança a página");
ok(G("listRecords", { status: "all", token: adminTok, limit: "200", offset: "0" }).rows.length === 5, "limit maior que total retorna tudo");
const pgPend = G("listPending", { token: adminTok, limit: "1", offset: "0" });
ok(pgPend.total >= 1 && pgPend.rows.length === 1, "listPending pagina");
const pgUsers = G("listUsers", { token: adminTok, limit: "2", offset: "0" });
ok(pgUsers.total >= 2 && pgUsers.rows.length === 2, "listUsers pagina");
ok(Array.isArray(G("listRecords", { status: "approved" })), "sem limit mantém array puro");
ok(G("listRecords", { status: "all", token: adminTok, best: "1" }).every(r => r.is_best === "TRUE"), "best=1 filtra");
ok(G("listRecords", { status: "approved", community: "0" }).every(r => Number(r.community || 0) === 0), "community=0 filtra não votados");

console.log("== comunidade: pontos e votação ==");
const voters = [];
for (let v = 1; v <= 3; v++) {
  P("register", { nickname: "Vot" + v, email: `vot${v}@test.com`, password: strongPass });
  const lg = P("login", { email: `vot${v}@test.com`, password: strongPass });
  P("setUserStatus", { token: adminTok, id: lg.user.id, status: "active" });
  [0, 1].forEach((i) => {
    const s = P("submitRecord", { token: lg.token, course_id: "blue_lagoon", power_value: 283 + (v - 1) * 2 + i, score: -10 - i, method: "com_ajuda", wind: "normal" });
    P("validateRecord", { token: adminTok, id: s.id, status: "approved" });
  });
  voters.push({ token: lg.token });
}
ok(G("getMe", { token: voters[0].token }).points === 20, "votante soma 20 pontos");
const cand = P("submitRecord", { token: userTok, course_id: "blue_water", power_value: 246, score: -28, pang: 9000, method: "com_ajuda", wind: "normal" });
P("validateRecord", { token: adminTok, id: cand.id, status: "approved" });
ok(G("getMe", { token: userTok }).points >= 10, "dono soma pontos do admin-ok");
ok(P("vote", { token: userTok, id: cand.id, vote: "approve" }).erro, "dono não vota no próprio");
ok(P("vote", { token: tok2, id: cand.id, vote: "approve" }).erro, "sem pontos não vota");
ok(P("vote", { token: voters[0].token, id: cand.id, vote: "approve" }).decided !== "approved", "1 voto não decide");
P("vote", { token: voters[1].token, id: cand.id, vote: "approve" });
const v3 = P("vote", { token: voters[2].token, id: cand.id, vote: "approve" });
ok(v3.decided === "approved" && v3.tally.approve === 60, "3 votos (60) aprovam");
const fin = G("listRecords", { user_id: userId, status: "all", token: userTok }).find((r) => r.id === cand.id);
ok(fin.status === "pending" && Number(fin.community) === 1, "aprovado volta p/ pending c/ flag");
ok(G("getMe", { token: userTok }).points >= 35, "dono soma +25 da comunidade");
const cand2 = P("submitRecord", { token: userTok, course_id: "blue_water", power_value: 247, score: -15, method: "com_ajuda", wind: "normal" });
P("validateRecord", { token: adminTok, id: cand2.id, status: "approved" });
voters.forEach((x) => P("vote", { token: x.token, id: cand2.id, vote: "reject" }));
const rej2 = G("listRecords", { user_id: userId, status: "all", token: userTok }).find((r) => r.id === cand2.id);
  ok(rej2.status === "pending" && Number(rej2.community) === -1, "rejeitado volta p/ fila do admin com flag -1");
P("validateRecord", { token: adminTok, id: cand.id, status: "approved" });
ok(G("listRecords", { community: "1" }).some((r) => r.id === cand.id), "index lista community=1");
ok(G("listRecords", { user_id: userId, status: "all", token: userTok }).find((r) => r.id === cand.id).is_best === "TRUE", "final do admin marca best");
ok(!G("listRecords", { community: "1" }).some((r) => r.id === cand2.id), "rejeitado fora do index");
const t2 = G("tallies", { ids: [cand.id, cand2.id, "inexistente"].join(",") });
ok(t2[cand.id].approve === 60 && t2[cand.id].voters === 3, "tallies em lote soma aprovações");
ok(t2[cand2.id].reject === 60 && t2[cand2.id].voters === 3, "tallies em lote soma rejeitos");
  ok(t2["inexistente"].approve === 0 && t2["inexistente"].voters === 0, "tallies id desconhecido zera");
  ok(P("reopenVote", { token: userTok, id: cand2.id }).erro, "reopen bloqueia user comum");
  ok(P("reopenVote", { token: adminTok, id: cand.id }).erro, "reopen bloqueia record publicado no index");
  ok(P("reopenVote", { token: adminTok, id: cand2.id }).status === "ok", "admin reabre votação");
  const re = G("listRecords", { user_id: userId, status: "all", token: userTok }).find((r) => r.id === cand2.id);
  ok(re.status === "approved" && Number(re.community) === 0, "reaberto volta aprovado p/ community=0");
  ok(G("tallies", { ids: cand2.id })[cand2.id].voters === 0, "reabrir apaga votos antigos");
  ok(P("validateRecord", { token: adminTok, id: cand2.id, status: "approved", community: "-1" }).status === "ok", "admin reprova comunidade (-1)");
  ok(Number(G("listRecords", { user_id: userId, status: "all", token: userTok }).find((r) => r.id === cand2.id).community) === -1, "flag -1 salva pelo admin");
  ok(P("validateRecord", { token: adminTok, id: cand2.id, status: "approved", community: "0" }).status === "ok", "admin volta p/ não votado (0)");

  console.log("== comunidade: rejeição vira pedido no admin ==");
  const cand3 = P("submitRecord", { token: userTok, course_id: "blue_water", power_value: 251, score: -16, method: "com_ajuda", wind: "normal" });
  P("validateRecord", { token: adminTok, id: cand3.id, status: "approved" });
  voters.forEach((x) => P("vote", { token: x.token, id: cand3.id, vote: "reject" }));
  const rej3 = G("listRecords", { user_id: userId, status: "all", token: userTok }).find((r) => r.id === cand3.id);
  ok(rej3.status === "pending" && Number(rej3.community) === -1, "rejeitado volta p/ pending com flag -1");
  ok(G("listPending", { token: adminTok }).some((r) => r.id === cand3.id), "rejeitado aparece na fila do admin");

  console.log("== comunidade: record do admin reprovado e reavaliação ==");
  const admRej = P("submitRecord", { token: adminTok, course_id: "blue_lagoon", power_value: 255, score: -19, method: "com_ajuda", wind: "normal" });
  P("validateRecord", { token: adminTok, id: admRej.id, status: "approved" });
  ok(P("vote", { token: adminTok, id: admRej.id, vote: "approve" }).erro, "admin não vota no próprio record");
  voters.forEach((x) => P("vote", { token: x.token, id: admRej.id, vote: "reject" }));
  const ar = G("listRecords", { user_id: "admin-1", status: "all", token: adminTok }).find((r) => r.id === admRej.id);
  ok(ar.status === "pending" && Number(ar.community) === -1, "record do admin reprovado vira pedido");
  ok(P("reopenVote", { token: adminTok, id: admRej.id }).status === "ok", "admin reabre do pending");
  const ar2 = G("listRecords", { user_id: "admin-1", status: "all", token: adminTok }).find((r) => r.id === admRej.id);
  ok(ar2.status === "approved" && Number(ar2.community) === 0, "reaberto volta aprovado/0 p/ votar de novo");
  voters.forEach((x) => P("vote", { token: x.token, id: admRej.id, vote: "approve" }));
  const ar3 = G("listRecords", { user_id: "admin-1", status: "all", token: adminTok }).find((r) => r.id === admRej.id);
  ok(ar3.status === "pending" && Number(ar3.community) === 1, "revotação aprova e volta p/ final do admin");
  ok(P("reopenVote", { token: adminTok, id: admRej.id }).status === "ok", "final devolvido reabre p/ votar");
  const ar4 = G("listRecords", { user_id: "admin-1", status: "all", token: adminTok }).find((r) => r.id === admRej.id);
  ok(ar4.status === "approved" && Number(ar4.community) === 0, "devolvido volta aprovado/0");
  ok(G("tallies", { ids: admRej.id })[admRej.id].voters === 0, "devolução apaga votos");

  console.log("== comunidade: dono edita votado zera votos ==");
  ok(P("validateRecord", { token: adminTok, id: cand3.id, status: "approved" }).status === "ok", "admin confirma rejeição");
  const cf = G("listRecords", { user_id: userId, status: "all", token: userTok }).find((r) => r.id === cand3.id);
  ok(cf.status === "approved" && Number(cf.community) === -1, "rejeição confirmada (approved/-1, fora da fila)");
  ok(P("updateRecord", { token: userTok, id: cand3.id, data: { video_url: "https://youtu.be/novo" } }).status === "ok", "dono edita reprovado");
  const cf2 = G("listRecords", { user_id: userId, status: "all", token: userTok }).find((r) => r.id === cand3.id);
  ok(cf2.status === "pending" && Number(cf2.community) === 0 && cf2.edited === "TRUE", "edição em votado zera e volta como novo pedido");
  ok(G("tallies", { ids: cand3.id })[cand3.id].voters === 0, "votos da versão antiga apagados");
  ok(G("listPending", { token: adminTok }).some((r) => r.id === cand3.id), "novo pedido na fila do admin");

  console.log("== comunidade: raiva + apelação sem editar ==");
  ok(P("validateRecord", { token: adminTok, id: cand3.id, status: "approved", community: "-1" }).status === "ok", "admin reprova de novo p/ cenário");
  ok(P("appealVote", { token: voters[0].token, id: cand3.id }).erro, "só o dono apela");
  ok(P("appealVote", { token: userTok, id: cand.id }).erro, "sem rejeição confirmada não apela");
  ok(P("appealVote", { token: userTok, id: cand3.id }).status === "ok", "dono pede reavaliação sem editar");
  const ap = G("listRecords", { user_id: userId, status: "all", token: userTok }).find((r) => r.id === cand3.id);
  ok(ap.status === "pending" && Number(ap.community) === -1, "apelação volta p/ fila sem mudar dado");
  ok(G("listPending", { token: adminTok }).some((r) => r.id === cand3.id), "apelação na fila do admin");
  ok(P("appealVote", { token: userTok, id: cand3.id }).erro, "sem spam: já na fila não apela");
  ok(P("updateRecord", { token: userTok, id: cand3.id, data: { pang: 777 } }).status === "ok", "dono edita com apelação pendente");
  const ap2 = G("listRecords", { user_id: userId, status: "all", token: userTok }).find((r) => r.id === cand3.id);
  ok(ap2.status === "pending" && Number(ap2.community) === 0 && Number(ap2.pang) === 777, "edição invalida a apelação e volta como novo pedido");

  console.log("== comunidade: reaberto vota a versão nova ==");
  ok(P("validateRecord", { token: adminTok, id: cand3.id, status: "approved" }).status === "ok", "admin aprova versão nova");
  voters.forEach((x) => P("vote", { token: x.token, id: cand3.id, vote: "approve" }));
  const ap3 = G("listRecords", { user_id: userId, status: "all", token: userTok }).find((r) => r.id === cand3.id);
  ok(ap3.status === "pending" && Number(ap3.community) === 1, "comunidade decide sobre a versão nova");
  ok(G("tallies", { ids: cand3.id })[cand3.id].approve === 60, "só votos da versão nova contam");

const admCand = P("submitRecord", { token: adminTok, course_id: "blue_water", power_value: 249, score: -14, method: "com_ajuda", wind: "normal" });
P("validateRecord", { token: adminTok, id: admCand.id, status: "approved", community_ok: true });
const adminPts = G("getMe", { token: adminTok }).points;
const open = P("submitRecord", { token: userTok, course_id: "blue_water", power_value: 248, score: -13, method: "com_ajuda", wind: "normal" });
P("validateRecord", { token: adminTok, id: open.id, status: "approved" });
const va = P("vote", { token: adminTok, id: open.id, vote: "approve" });
ok(adminPts >= 10 && va.status === "ok" && va.tally.approve === adminPts && va.tally.voters === 1 && !va.decided, "admin pode votar (peso = pontos)");

console.log("== método ==");
const VT = voters[0].token;
ok(P("submitRecord", { token: VT, course_id: "blue_water", power_value: 289, score: -25 }).erro, "submit sem método bloqueia");
ok(P("submitRecord", { token: VT, course_id: "blue_water", power_value: 289, score: -25, method: "sem_ajuda" }).erro, "sem_ajuda sem vídeo bloqueia");
const m1 = P("submitRecord", { token: VT, course_id: "blue_water", power_value: 289, score: -25, method: "sem_ajuda", wind: "normal", video_url: "https://youtu.be/m1" });
const m2 = P("submitRecord", { token: VT, course_id: "blue_water", power_value: 290, score: -26, method: "com_ajuda", wind: "normal" });
ok(m1.status === "ok" && m2.status === "ok", "submits por método");
P("validateRecord", { token: adminTok, id: m1.id, status: "approved", community_ok: true });
P("validateRecord", { token: adminTok, id: m2.id, status: "approved", community_ok: true });
const mcat = (id) => G("listRecords", { status: "approved", token: adminTok }).find((r) => r.id === id);
ok(mcat(m1.id).is_best === "TRUE" && mcat(m2.id).is_best === "TRUE", "best separado por método");
const m3 = P("submitRecord", { token: VT, course_id: "blue_water", power_value: 289, score: -20, method: "com_ajuda", wind: "normal" });
ok(m3.status === "ok" && !m3.updated && m3.id !== m1.id, "método diferente não é duplicado");
ok(G("listRecords", { method: "sem_ajuda", token: adminTok }).every((r) => String(r.method) === "sem_ajuda"), "filtro por método");

console.log("== proposta de melhoria ==");
const prop = P("submitRecord", { token: userTok, course_id: "blue_water", power_value: 246, score: -29, pang: 9500, method: "com_ajuda", wind: "normal", video_url: "https://youtu.be/p" });
ok(prop.proposal === true && prop.id !== cand.id, "melhoria de live vira proposta");
const orig = () => G("listRecords", { user_id: userId, status: "all", token: userTok }).find((r) => r.id === cand.id);
ok(orig().score === "-28" && orig().status === "approved", "original segue live");
const pts0 = G("getMe", { token: userTok }).points;
P("validateRecord", { token: adminTok, id: prop.id, status: "approved" });
ok(G("getMe", { token: userTok }).points === pts0 + 5, "aprovar proposta paga metade (+5)");
voters.forEach((x) => P("vote", { token: x.token, id: prop.id, vote: "approve" }));
const propAfter = G("listRecords", { user_id: userId, status: "all", token: userTok }).find((r) => r.id === prop.id);
ok(propAfter.status === "pending" && Number(propAfter.community) === 1, "proposta volta p/ fila");
ok(G("getMe", { token: userTok }).points === pts0 + 5 + 12, "comunidade paga metade (+12)");
P("validateRecord", { token: adminTok, id: prop.id, status: "approved" });
const merged = G("listRecords", { user_id: userId, status: "all", token: userTok });
ok(!merged.some((r) => r.id === prop.id), "proposta some após merge");
const fin2 = merged.find((r) => r.id === cand.id);
ok(fin2.score === "-29" && Number(fin2.pang) === 9500 && fin2.is_best === "TRUE", "original atualizado e best");
const prop2 = P("updateRecord", { token: userTok, id: cand.id, data: { score: -30 } });
ok(prop2.proposal === true, "edit de live vira proposta");
P("validateRecord", { token: adminTok, id: prop2.id, status: "rejected" });
const afterRej = G("listRecords", { user_id: userId, status: "all", token: userTok });
ok(afterRej.find((r) => r.id === cand.id).score === "-29", "original intacto após reject");
ok(afterRej.find((r) => r.id === prop2.id).status === "rejected", "proposta rejeitada no histórico");
const proofProp = P("updateRecord", { token: userTok, id: cand.id, data: { screenshot_url: "https://example.com/prova.png" } });
ok(proofProp.proposal === true && proofProp.communityReview === false, "prova de live passa só pelo admin");
ok(G("listRecords", { user_id: userId, status: "all", token: userTok }).find((r) => r.id === proofProp.id).community === "1", "proposta de prova preserva comunidade");
ok(P("validateRecord", { token: adminTok, id: proofProp.id, status: "approved" }).merged === true, "admin aplica prova sem nova votação");
ok(G("listRecords", { user_id: userId, status: "all", token: userTok }).find((r) => r.id === cand.id).screenshot_url === "https://example.com/prova.png", "prova aprovada atualiza original");
const admRec = P("submitRecord", { token: adminTok, course_id: "blue_lagoon", power_value: 250, score: -18, method: "com_ajuda", wind: "normal" });
P("validateRecord", { token: adminTok, id: admRec.id, status: "approved", community_ok: true });
const admProp = P("updateRecord", { token: adminTok, id: admRec.id, data: { score: -19 } });
ok(admProp.proposal === true, "dono-admin editando live vira proposta");
ok(G("listRecords", { user_id: "admin-1", status: "all", token: adminTok }).find((r) => r.id === admRec.id).score === "-18", "live do admin intacto");
ok(P("updateRecord", { token: adminTok, id: cand.id, data: { note: "ok" } }).status === "ok", "admin em terceiro altera direto");
const d1 = P("updateRecord", { token: adminTok, id: admRec.id, direct: true, data: { score: -17 } });
const admAfter = G("listRecords", { user_id: "admin-1", status: "all", token: adminTok }).find((r) => r.id === admRec.id);
ok(d1.status === "ok" && !d1.proposal && admAfter.score === "-17" && admAfter.status === "approved", "direct do Gerenciar altera o próprio");
ok(P("updateRecord", { token: userTok, id: cand.id, direct: true, data: { score: -32 } }).proposal === true, "direct de comum é ignorado");
P("validateRecord", { token: adminTok, id: admProp.id, status: "rejected" });
ok(P("updateRecord", { token: adminTok, id: admProp.id, data: { score: -21 } }).status === "ok", "admin reedita a própria");
ok(G("listPending", { token: adminTok }).some((r) => r.id === admProp.id), "reedição do admin volta p/ fila");

console.log("== vento ==");
ok(P("submitRecord", { token: VT, course_id: "blue_water", power_value: 288, score: -25, method: "com_ajuda" }).erro, "submit sem vento bloqueia");
ok(P("submitRecord", { token: VT, course_id: "blue_water", power_value: 288, score: -25, method: "com_ajuda", wind: "forte" }).erro, "vento inválido bloqueia");
const w1 = P("submitRecord", { token: VT, course_id: "blue_water", power_value: 287, score: -24, method: "com_ajuda", wind: "natural" });
const w2 = P("submitRecord", { token: VT, course_id: "blue_water", power_value: 288, score: -27, method: "com_ajuda", wind: "normal" });
ok(w1.status === "ok" && w2.status === "ok", "submits por vento");
P("validateRecord", { token: adminTok, id: w1.id, status: "approved", community_ok: true });
P("validateRecord", { token: adminTok, id: w2.id, status: "approved", community_ok: true });
const wcat = (id) => G("listRecords", { status: "approved", token: adminTok }).find((r) => r.id === id);
ok(wcat(w1.id).is_best === "TRUE" && wcat(w2.id).is_best === "TRUE", "best separado por vento");
const w3 = P("submitRecord", { token: VT, course_id: "blue_water", power_value: 287, score: -20, method: "com_ajuda", wind: "normal" });
ok(w3.status === "ok" && !w3.updated && w3.id !== w1.id, "vento diferente não é duplicado");
ok(G("listRecords", { wind: "natural", token: adminTok }).every((r) => String(r.wind) === "natural"), "filtro por vento");

console.log("== blindagens ==");
const propWind = G("listRecords", { user_id: userId, status: "all", token: userTok }).find((r) => r.id === prop.id || r.edit_of === cand.id);
ok(!propWind || propWind.wind === "normal", "proposta preserva o vento");
ok(P("validateRecord", { token: adminTok, id: cand.id, status: "maybe" }).erro === "status inválido", "validate rejeita status inválido");
ok(P("submitRecord", { token: VT, course_id: "blue_water", power_value: 250, method: "com_ajuda", wind: "normal" }).erro, "submit sem score bloqueia");
const scoreBefore = G("listRecords", { user_id: "admin-1", status: "all", token: adminTok }).find((r) => r.id === admRec.id).score;
ok(P("updateRecord", { token: adminTok, id: admRec.id, direct: true, data: { score: -100, method: "x" } }).erro, "update com método inválido bloqueia");
ok(G("listRecords", { user_id: "admin-1", status: "all", token: adminTok }).find((r) => r.id === admRec.id).score === scoreBefore, "erro não deixa escrita parcial");
const inact = P("upsertBand", { token: adminTok, data: { label: "inativa", min: 1, max: 2, active: "FALSE" } });
ok(P("submitRecord", { token: VT, course_id: "blue_water", power_value: 1, score: -5, method: "com_ajuda", wind: "normal", powerband_id: inact.id }).erro === "Faixa desativada", "submit em faixa inativa bloqueia");
ok(P("deleteBand", { token: adminTok, id: inact.id }).status === "ok", "limpa faixa inativa de teste");

console.log("== integridade de edição e reenvio ==");
const draftCheck = P("submitRecord", { token: VT, course_id: "blue_lagoon", power_value: 246, score: -10, method: "sem_ajuda", wind: "normal", video_url: "https://youtu.be/proof" });
const draftSnapshot = () => G("listRecords", { token: VT, user_id: G("getMe", { token: VT }).id, status: "all" }).find(r => r.id === draftCheck.id);
const beforeInvalid = JSON.stringify(draftSnapshot());
ok(P("updateRecord", { token: VT, id: draftCheck.id, data: { score: -50, video_url: "" } }).erro, "edição sem vídeo obrigatório bloqueia");
ok(JSON.stringify(draftSnapshot()) === beforeInvalid, "vídeo inválido não deixa score alterado");
ok(P("updateRecord", { token: VT, id: draftCheck.id, data: { score: -50, power_value: 99999 } }).erro, "edição com força sem faixa bloqueia");
ok(JSON.stringify(draftSnapshot()) === beforeInvalid, "faixa inválida não deixa escrita parcial");
ok(P("submitRecord", { token: VT, course_id: "inexistente", power_value: 246, score: -10, method: "com_ajuda", wind: "normal" }).erro, "campo inexistente não aceita record");
ok(P("submitRecord", { token: VT, course_id: "blue_water", power_value: 246, score: null, method: "com_ajuda", wind: "normal" }).erro, "score nulo não vira zero");
P("validateRecord", { token: adminTok, id: draftCheck.id, status: "approved" });
P("vote", { token: voters[1].token, id: draftCheck.id, vote: "approve" });
ok(G("tally", { id: draftCheck.id }).voters === 1, "versão original recebeu voto");
P("submitRecord", { token: VT, course_id: "blue_lagoon", power_value: 246, score: -11, method: "sem_ajuda", wind: "normal", video_url: "https://youtu.be/new-proof" });
ok(G("tally", { id: draftCheck.id }).voters === 0, "reenvio invalida votos da versão anterior");
ok(Number(draftSnapshot().community) === 0 && draftSnapshot().status === "pending", "reenvio exige nova revisão");
ok(G("toString").erro && P("constructor").erro, "roteador não executa propriedades herdadas");

console.log("== logout ==");
ok(P("changePassword", { token: userTok, current_password: "errada", new_password: "NovaSenha1!" }).erro, "troca de senha exige senha atual");
ok(P("changePassword", { token: userTok, current_password: strongPass, new_password: "NovaSenha1!" }).status === "ok", "troca de senha atualiza hash");
ok(P("login", { email: "p1@test.com", password: "NovaSenha1!" }).status === "ok", "login aceita nova senha");
const resetReg = P("register", { nickname: "ResetSenha", email: "reset@test.com", password: strongPass });
const resetToken = P("login", { email: "reset@test.com", password: strongPass }).token;
ok(P("adminResetPassword", { token: userTok, id: resetReg.user.id, new_password: "AdminNova1!" }).erro, "reset admin bloqueia user comum");
ok(P("adminResetPassword", { token: adminTok, id: resetReg.user.id, new_password: "AdminNova1!" }).status === "ok", "admin redefine senha de usuário");
ok(P("login", { email: "reset@test.com", password: strongPass }).erro && P("login", { email: "reset@test.com", password: "AdminNova1!" }).status === "ok", "reset invalida senha anterior");
ok(G("getMe", { token: resetToken }).erro, "reset encerra sessões do usuário");
const deleteReg = P("register", { nickname: "Excluir", email: "delete@test.com", password: strongPass });
const deleteTok = P("login", { email: "delete@test.com", password: strongPass }).token;
ok(P("deleteMe", { token: deleteTok, email: "outro@test.com", password: strongPass }).erro, "excluir exige e-mail da própria conta");
ok(P("deleteMe", { token: deleteTok, email: "delete@test.com", password: strongPass }).status === "ok", "usuário exclui a própria conta");
ok(!G("listUsers", { token: adminTok }).some((u) => u.id === deleteReg.user.id), "conta excluída some da lista admin");
ok(P("logout", { token: userTok }).status === "ok", "logout ok");
ok(G("getMe", { token: userTok }).erro, "token invalidado após logout");

console.log("== frontend escaping (XSS) ==");
const { execFileSync } = require("node:child_process");
execFileSync(process.execPath, ["--test", "tests/frontend.test.mjs", "tests/domain.test.js"], { stdio: "inherit" });

console.log(`\n${pass} ok, ${fail} falhas`);
process.exit(fail ? 1 : 0);
