const fs = require('node:fs');
const path = require('node:path');
const root = path.join(__dirname, '..', 'backend');
const files = ['modules/records/domain/record.js', 'modules/records/domain/ranking.js', 'modules/community/domain/voting.js', 'modules/identity/domain/points.js', 'infrastructure/google-apps-script.js', ...['identity', 'catalog', 'records', 'community'].map(name => `modules/${name}/application/service.js`), 'composition.js', 'adapters/http.js'];
const output = '// GENERATED by node scripts/build-backend.js. Edit backend/src instead.\n\n' + files.map(file => `// --- ${file} ---\n${fs.readFileSync(path.join(root, 'src', file), 'utf8')}`).join('\n');
if (process.argv.includes('--check')) {
  if (fs.readFileSync(path.join(root, 'Code.gs'), 'utf8') !== output) throw new Error('Backend bundle is stale. Run npm run build:backend.');
} else fs.writeFileSync(path.join(root, 'Code.gs'), output);
